### ISSUE TITLE
Docker-worker artifact build failing

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#2808]
```
[13:30:37] Build docker-worker artifacts: + NODE_VERSION=12.11.0
[13:30:37] Build docker-worker artifacts: + mkdir /tmp/tmp.FzjUXfGDpX/node
[13:30:37] Build docker-worker artifacts: + curl https://nodejs.org/dist/v12.11.0/node-v12.11.0-linux-x64.tar.xz
[13:30:37] Build docker-worker artifacts: + tar -C /tmp/tmp.FzjUXfGDpX/node --strip-components=1 -xJf -
[13:30:37] Build docker-worker artifacts:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[13:30:37] Build docker-worker artifacts:                                  Dload  Upload   Total   Spent    Left  Speed
100 13.3M  100 13.3M    0     0  2395k      0  0:00:05  0:00:05 --:--:-- 1933k
[13:30:43] Build docker-worker artifacts: + curl -L https://yarnpkg.com/latest.tar.gz
[13:30:43] Build docker-worker artifacts: + tar --transform 's|yarn-[^/]*/|yarn/|' -C /tmp/tmp.FzjUXfGDpX -zvxf -
[13:30:43] Build docker-worker artifacts:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[13:30:43] Build docker-worker artifacts:                                  Dload  Upload   Total   Spent    Left  Speed
100    57  100    57    0     0    504      0 --:--:-- --:--:-- --:--:--   504
100    93  100    93    0     0    375      0 --:--:-- --:--:-- --:--:--  2735
100   630  100   630    0     0   1510      0 --:--:-- --:--:-- --:--:--  1510
[13:30:43] Build docker-worker artifacts: yarn-v1.22.4/LICENSE
[13:30:43] Build docker-worker artifacts: yarn-v1.22.4/README.md
[13:30:43] Build docker-worker artifacts: yarn-v1.22.4/bin/
[13:30:43] Build docker-worker artifacts: yarn-v1.22.4/bin/yarn
[13:30:43] Build docker-worker artifacts: yarn-v1.22.4/bin/yarn.js
[13:30:43] Build docker-worker artifacts: yarn-v1.22.4/bin/yarnpkg
[13:30:43] Build docker-worker artifacts: yarn-v1.22.4/bin/yarn.cmd
[13:30:43] Build docker-worker artifacts: yarn-v1.22.4/bin/yarnpkg.cmd
[13:30:43] Build docker-worker artifacts: yarn-v1.22.4/lib/
[13:30:43] Build docker-worker artifacts: yarn-v1.22.4/lib/cli.js
100 1215k  100 1215k    0     0  1638k      0 --:--:-- --:--:-- --:--:-- 1638k
[13:30:44] Build docker-worker artifacts: yarn-v1.22.4/lib/v8-compile-cache.js
[13:30:44] Build docker-worker artifacts: yarn-v1.22.4/package.json
[13:30:44] Build docker-worker artifacts: + PATH=/tmp/tmp.FzjUXfGDpX/node/bin:/tmp/tmp.FzjUXfGDpX/node_modules/.bin:/tmp/yarn--1589290236600-0.5427373318398774:/task_1589290110/taskcluster/node_modules/.bin:/usr/local/share/.config/yarn/link/node_modules/.bin:/task_1589290110/taskcluster/node_modules/.bin:/home/task_1589290110/.nvm/versions/node/v12.16.3/libexec/lib/node_modules/n
pm/bin/node-gyp-bin:/home/task_1589290110/.nvm/versions/node/v12.16.3/lib/node_modules/npm/bin/node-gyp-bin:/home/task_1589290110/.nvm/versions/node/v12.16.3/bin/node_modules/npm/bin/node-gyp-bin:/home/task_1589290110/.yarn/bin:/home/task_1589290110/.config/yarn/global/node_modules/.bin:/home/task_1589290110/.nvm/versions/node/v12.16.3/bin:/task_1589290110/go/go/bin:/task_15892901
10/go/path/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
[13:30:44] Build docker-worker artifacts: + cd /tmp/tmp.FzjUXfGDpX
[13:30:44] Build docker-worker artifacts: + ./yarn/bin/yarn install --dev
[13:30:46] Build docker-worker artifacts: [1/4] Resolving packages...
[13:30:47] Build docker-worker artifacts: [2/4] Fetching packages...
[13:31:54] Build docker-worker artifacts: [3/4] Linking dependencies...
[13:32:07] Build docker-worker artifacts: [4/4] Building fresh packages...
[13:32:09] Build docker-worker artifacts: error /tmp/tmp.FzjUXfGDpX/node_modules/fs-ext: Command failed.
[13:32:09] Build docker-worker artifacts: Exit code: 1
[13:32:09] Build docker-worker artifacts: Command: node-gyp configure build
[13:32:09] Build docker-worker artifacts: Arguments: 
[13:32:09] Build docker-worker artifacts: Directory: /tmp/tmp.FzjUXfGDpX/node_modules/fs-ext
[13:32:09] Build docker-worker artifacts: Output:
[13:32:09] Build docker-worker artifacts: gyp info it worked if it ends with ok
[13:32:09] Build docker-worker artifacts: gyp info using node-gyp@5.0.3
[13:32:09] Build docker-worker artifacts: gyp info using node@12.11.0 | linux | x64
[13:32:09] Build docker-worker artifacts: gyp info find Python using Python version 2.7.17 found at "/usr/bin/python"
[13:32:09] Build docker-worker artifacts: gyp http GET https://nodejs.org/download/release/v12.11.0/node-v12.11.0-headers.tar.gz
[13:32:09] Build docker-worker artifacts: gyp http 200 https://nodejs.org/download/release/v12.11.0/node-v12.11.0-headers.tar.gz
[13:32:09] Build docker-worker artifacts: gyp http GET https://nodejs.org/download/release/v12.11.0/SHASUMS256.txt
[13:32:09] Build docker-worker artifacts: gyp http 200 https://nodejs.org/download/release/v12.11.0/SHASUMS256.txt
[13:32:09] Build docker-worker artifacts: gyp info spawn /usr/bin/python
[13:32:09] Build docker-worker artifacts: gyp info spawn args [
[13:32:09] Build docker-worker artifacts: gyp info spawn args   '/tmp/tmp.FzjUXfGDpX/node/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
[13:32:09] Build docker-worker artifacts: gyp info spawn args   'binding.gyp',
[13:32:09] Build docker-worker artifacts: gyp info spawn args   '-f',
[13:32:09] Build docker-worker artifacts: gyp info spawn args   'make',
[13:32:09] Build docker-worker artifacts: gyp info spawn args   '-I',
[13:32:09] Build docker-worker artifacts: gyp info spawn args   '/tmp/tmp.FzjUXfGDpX/node_modules/fs-ext/build/config.gypi',
[13:32:09] Build docker-worker artifacts: gyp info spawn args   '-I',
[13:32:09] Build docker-worker artifacts: gyp info spawn args   '/tmp/tmp.FzjUXfGDpX/node/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
[13:32:09] Build docker-worker artifacts: gyp info spawn args   '-I',
[13:32:09] Build docker-worker artifacts: gyp info spawn args   '/home/task_1589290110/.cache/node-gyp/12.11.0/include/node/common.gypi',
[13:32:09] Build docker-worker artifacts: gyp info spawn args   '-Dlibrary=shared_library',
[13:32:09] Build docker-worker artifacts: gyp info spawn args   '-Dvisibility=default',
[13:32:09] Build docker-worker artifacts: gyp info spawn args   '-Dnode_root_dir=/home/task_1589290110/.cache/node-gyp/12.11.0',
[13:32:09] Build docker-worker artifacts: gyp info spawn args   '-Dnode_gyp_dir=/tmp/tmp.FzjUXfGDpX/node/lib/node_modules/npm/node_modules/node-gyp',
[13:32:09] Build docker-worker artifacts: gyp info spawn args   '-Dnode_lib_file=/home/task_1589290110/.cache/node-gyp/12.11.0/<(target_arch)/node.lib',
[13:32:09] Build docker-worker artifacts: gyp info spawn args   '-Dmodule_root_dir=/tmp/tmp.FzjUXfGDpX/node_modules/fs-ext',
[13:32:09] Build docker-worker artifacts: gyp info spawn args   '-Dnode_engine=v8',
[13:32:09] Build docker-worker artifacts: gyp info spawn args   '--depth=.',
[13:32:09] Build docker-worker artifacts: gyp info spawn args   '--no-parallel',
[13:32:09] Build docker-worker artifacts: gyp info spawn args   '--generator-output',
[13:32:09] Build docker-worker artifacts: gyp info spawn args   'build',
[13:32:09] Build docker-worker artifacts: gyp info spawn args   '-Goutput_dir=.'
[13:32:09] Build docker-worker artifacts: gyp info spawn args ]
[13:32:09] Build docker-worker artifacts: gyp ERR! build error 
[13:32:09] Build docker-worker artifacts: gyp ERR! stack Error: not found: make
[13:32:09] Build docker-worker artifacts: gyp ERR! stack     at getNotFoundError (/tmp/tmp.FzjUXfGDpX/node/lib/node_modules/npm/node_modules/which/which.js:13:12)
[13:32:09] Build docker-worker artifacts: gyp ERR! stack     at F (/tmp/tmp.FzjUXfGDpX/node/lib/node_modules/npm/node_modules/which/which.js:68:19)
[13:32:09] Build docker-worker artifacts: gyp ERR! stack     at E (/tmp/tmp.FzjUXfGDpX/node/lib/node_modules/npm/node_modules/which/which.js:80:29)
[13:32:09] Build docker-worker artifacts: gyp ERR! stack     at /tmp/tmp.FzjUXfGDpX/node/lib/node_modules/npm/node_modules/which/which.js:89:16
[13:32:09] Build docker-worker artifacts: gyp ERR! stack     at /tmp/tmp.FzjUXfGDpX/node/lib/node_modules/npm/node_modules/isexe/index.js:42:5
[13:32:09] Build docker-worker artifacts: gyp ERR! stack     at /tmp/tmp.FzjUXfGDpX/node/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
[13:32:09] Build docker-worker artifacts: gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:169:21)
[13:32:09] Build docker-worker artifacts: gyp ERR! System Linux 5.3.0-1017-aws
[13:32:09] Build docker-worker artifacts: gyp ERR! command "/tmp/tmp.FzjUXfGDpX/node/bin/node" "/tmp/tmp.FzjUXfGDpX/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
[13:32:09] Build docker-worker artifacts: gyp ERR! cwd /tmp/tmp.FzjUXfGDpX/node_modules/fs-ext
[13:32:09] Build docker-worker artifacts: gyp ERR! node -v v12.11.0
[13:32:09] Build docker-worker artifacts: gyp ERR! node-gyp -v v5.0.3
[13:32:09] Build docker-worker artifacts: gyp ERR! not ok
[13:32:09] Build docker-worker artifacts: info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[13:32:09] Build docker-worker artifacts: + rm -rf /tmp/tmp.FzjUXfGDpX
[13:32:10] Build docker-worker artifacts: failed
[13:32:10] Build docker-worker artifacts: fail: Error: Nonzero exit status 1; 
```
This worked when I landed it, I think -- although looking back at #2789 the link to the staging run now points to a different run.

**Comment by djmitche** [comment]
This is failing to build fs-ext, and fs-ext is required because it's used to `flock` a file for communication with interactive tasks.

**Comment by djmitche** [comment]
I think there are three ways to fix this:
 * build a custom machine image that has python and build-essential installed, and run releases on that (we currently use the base generic-worker image)
 * install python and build-essential on the host at the beginning of the task (we install gox and a few other things too, in .taskcluster.yml)
 * run the docker-worker build in a docker image (the node image appears to have the necessary things already installed)
