### ISSUE TITLE
[docker-worker] intermittent file_artifact_test.js timeout

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#2951]
https://community-tc.services.mozilla.com/tasks/cCpAzB_gTVumPN_J3hrwsA/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FcCpAzB_gTVumPN_J3hrwsA%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log
```
  1) workers/docker-worker/test/integration/file_artifact_test.js (real)
       upload retry:
     Error: Timeout of 200000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/tester/git_checkout/workers/docker-worker/test/integration/file_artifact_test.js)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)
```

**Comment by djmitche** [comment]
https://community-tc.services.mozilla.com/tasks/FEAh5K_8RwWePqRYsbMeTw/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FFEAh5K_8RwWePqRYsbMeTw%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log

**Comment by djmitche** [comment]
This seems better?? weird.
