### ISSUE TITLE
smoketests sometimes fail with role-related issue

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#3224]
```
AssertionError [ERR_ASSERTION]: Expected values to be loosely deep-equal: (while executing task Create role and expand smoketest (--target roles))

[
  'assume:project:taskcluster:smoketest:cTTAcdksS6qEBLcszMA_4w:abc'
]

should loosely deep-equal

[
  'assume:project:taskcluster:smoketest:cTTAcdksS6qEBLcszMA_4w:abc',
  'project:taskcluster:smoketest:abc/*'
]
    at Object.run (/home/dustin/p/taskcluster/infrastructure/tooling/src/smoketest/checks/role.js:43:12)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async TaskGraph._runNode (/home/dustin/p/taskcluster/node_modules/console-taskgraph/src/taskgraph.js:184:18) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: [Array],
  expected: [Array],
  operator: 'deepEqual'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This happened at v32.0.0 and v33.0.0, and it's intermittent.  That check adds the role `project:taskcluster:smoketest:cTTAcdksS6qEBLcszMA_4w:abc` and then immediately expands it, so perhaps this is an issue of a delay in updating the resolvers.

**Comment by djmitche** [comment]
I think this is a known race condition: when `createRole` returns, other auth instances may not have updated to account for the new role yet.  Most deployments only have one auth instance, so this doesn't matter, but firefox-ci has a lot of them.  So I can only repro in firefox-ci.

This is a known characteristic of the API, and only affects this kind of test that expects immediate read-after-write consistency.  So probably the fix is to poll a little bit in the smoketest.
