### ISSUE TITLE
Worker manager CI test failing

### ISSUE THREAD

**Issue by helfi92** [taskcluster/taskcluster#3372]
```
  services/worker-manager/test/estimator_test.js
    ✓ empty estimation
    ✓ single estimation
    ✓ satisfied estimation
    ✓ scaling ratio 1:1 scale-up
    ✓ scaling ratio 1:1 scale-up with lesser max capacity
    ✓ scaling ratio 1:2 scale-up
    ✓ scaling ratio 1:2 scale-up with existing capacity
    1) over-satisfied estimation
    2) "after each" hook for "over-satisfied estimation"
  72 passing (7s)
  2 failing
  1) services/worker-manager/test/estimator_test.js
       over-satisfied estimation:
      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
3 !== 2
      + expected - actual
      -3
      +2
      
      at Context.<anonymous> (test/estimator_test.js:157:12)
  2) "after each" hook for "over-satisfied estimation":
     Error: Errors logged to monitor during test run:
{"desiredCapacity":1,"existingCapacity":50,"maxCapacity":1,"minCapacity":1,"pendingTasks":100,"requestedCapacity":0,"scalingRatio":1,"v":3,"workerPoolId":"foo/bar"}
{"desiredCapacity":1,"existingCapacity":50,"maxCapacity":1,"message":"Estimated existing capacity (pending and running) is much greater than max capacity","minCapacity":1,"name":"Error","pendingTasks":100,"requestedCapacity":0,"scalingRatio":1,"stack":"Error: Estimated existing capacity (pending and running) is much greater than max capacity\n    at Estimator.simple (/taskcluster/services/worker-manager/src/estimator.js:51:32)\n    at async Context.<anonymous> (/taskcluster/services/worker-manager/test/estimator_test.js:149:22)","v":1,"workerPoolId":"foo/bar"}
      at Context.<anonymous> (/taskcluster/libraries/testing/src/with-monitor.js:24:15)
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
```

https://community-tc.services.mozilla.com/tasks/XGuls8bZQc2bx2NS1U0WGQ/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FXGuls8bZQc2bx2NS1U0WGQ%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log

**Comment by djmitche** [comment]
I can't reproduce this locally.  It looks like it's a race condition in the timing of the worker scanner.

**Comment by djmitche** [comment]
This failed in the next test 5 days ago, but not in the test with the logging!
https://community-tc.services.mozilla.com/tasks/VgbSZoEATR6k5BuLBgY3uA/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FVgbSZoEATR6k5BuLBgY3uA%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log

**Comment by djmitche** [comment]
I haven't seen this again for a while :(
