### ISSUE TITLE
taskcluster-proxy fails with docker-worker 37.1.0

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#3521]
https://community-tc.services.mozilla.com/tasks/UxWAGXW5Q7WWKY3GeQqdEA/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FUxWAGXW5Q7WWKY3GeQqdEA%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log
```
[task 2020-09-16T17:44:14.566Z] ---
[task 2020-09-16T17:44:14.566Z] 
[task 2020-09-16T17:44:14.566Z] * method:     createTask
[task 2020-09-16T17:44:14.566Z] * errorCode:  MalformedPayload
[task 2020-09-16T17:44:14.566Z] * statusCode: 400
[task 2020-09-16T17:44:14.566Z] * time:       2020-09-16T17:44:14.395Z
[task 2020-09-16T17:44:14.585Z] 2020-09-16 17:44:14,585 - ERROR - Payload must be JSON with content-type: application/json got content-type: null
[task 2020-09-16T17:44:14.585Z] 
[task 2020-09-16T17:44:14.585Z] ---
[task 2020-09-16T17:44:14.585Z] 
[task 2020-09-16T17:44:14.585Z] * method:     createTask
[task 2020-09-16T17:44:14.585Z] * errorCode:  MalformedPayload
[task 2020-09-16T17:44:14.585Z] * statusCode: 400
[task 2020-09-16T17:44:14.585Z] * time:       2020-09-16T17:44:14.554Z
[task 2020-09-16T17:44:14.591Z] Traceback (most recent call last):
[task 2020-09-16T17:44:14.591Z]   File "/builds/worker/.local/lib/python2.7/site-packages/taskgraph/main.py", line 481, in main
[task 2020-09-16T17:44:14.592Z]     args.command(vars(args))
[task 2020-09-16T17:44:14.592Z]   File "/builds/worker/.local/lib/python2.7/site-packages/taskgraph/main.py", line 321, in decision
[task 2020-09-16T17:44:14.592Z]     taskgraph_decision(options)
[task 2020-09-16T17:44:14.592Z]   File "/builds/worker/.local/lib/python2.7/site-packages/taskgraph/decision.py", line 113, in taskgraph_decision
[task 2020-09-16T17:44:14.592Z]     create_tasks(tgg.graph_config, tgg.morphed_task_graph, tgg.label_to_taskid, tgg.parameters)
[task 2020-09-16T17:44:14.592Z]   File "/builds/worker/.local/lib/python2.7/site-packages/taskgraph/create.py", line 107, in create_tasks
[task 2020-09-16T17:44:14.592Z]     f.result()
[task 2020-09-16T17:44:14.592Z]   File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 455, in result
[task 2020-09-16T17:44:14.592Z]     return self.__get_result()
[task 2020-09-16T17:44:14.592Z]   File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/thread.py", line 63, in run
[task 2020-09-16T17:44:14.595Z]     result = self.fn(*self.args, **self.kwargs)
[task 2020-09-16T17:44:14.595Z]   File "/builds/worker/.local/lib/python2.7/site-packages/taskgraph/create.py", line 133, in create_task
[task 2020-09-16T17:44:14.595Z]     res.raise_for_status()
[task 2020-09-16T17:44:14.595Z]   File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 940, in raise_for_status
[task 2020-09-16T17:44:14.595Z]     raise HTTPError(http_error_msg, response=self)
[task 2020-09-16T17:44:14.595Z] HTTPError: 400 Client Error: Bad Request for url: http://taskcluster/queue/v1/task/Oz-P-HHAQaOW7fYaE4wk7Q
```

with these workers.  Presumably taskcluster-proxy is stripping content-type or something like that?

**Comment by djmitche** [comment]
taskcluster/monopacker#86 reverts to docker-worker 30.0.2, which might have been too far (we had been running 30.1.1).

**Comment by jwhitlock** [comment]
I dug into this, because I was auto-marked as a reviewer for PR #3597, and I don't think I've found anything deeper than @djmitche's intuition "Presumably taskcluster-proxy is stripping content-type or something like that?"

I compared the failed log to a recent successful run. I couldn't see any difference in the packages installed. The worker node type was identical. The failed task was in worker group ``us-east4``, and the successful task in ``us-east1``. The successful task was worker version ``30.1.1``, the failed was ``37.1.0``. 

Looking at the failures, it appeared 50 (out of 51 tasks) ``PUT`` requests to create a task failed because ``Content-Type`` wasn't set. There is not enough information if the 51st task succeeded, is associated with the traceback, or was not attempted due to dependencies.

One possibility is that ``taskgraph`` is setting the header most of the time but not in some cases. This was Python code, so I felt comfortable peeking at the details.

``taskgraph`` is installed from a revision from [May 13, 2020](https://hg.mozilla.org/ci/taskgraph/rev/cab4565345d0d0effa66f18fe91335dd6d744031), labelled "part 2: Simplify mobile into * ones - just like gecko does r=mtabara". The next commit is labelled "part 3: Make trust_domain scopes generic r=tomprince", which feels like we locked into a commit in the middle of a multi-commit update. Later changes appear to be API changes, such as [always passing a decision_task_id to create_tasks](https://hg.mozilla.org/ci/taskgraph/rev/8226c4cced0f76b2ae07fbca7da8d26be17b6b60), so an upgrade may require caution.

The [code that creates the task](https://hg.mozilla.org/ci/taskgraph/file/cab4565345d0d0effa66f18fe91335dd6d744031/src/taskgraph/create.py#l110) has not changed significantly:

```
res = session.put('http://taskcluster/queue/v1/task/{}'.format(task_id),
                  data=json.dumps(task_def))
```

The code's docstring calls out that ``http://taskcluster/queue`` is the proxy for calling the queue service with appropriate credentials.

``taskgraph`` uses requests 2.22.0, a fairly recent release (2019-05-15, with [2.24.0](https://requests.readthedocs.io/en/latest/community/updates/#id1) released 2020-06-17). The documentation [suggests an alternate call](https://requests.readthedocs.io/en/master/user/quickstart/#more-complicated-post-requests), supported by 2.22.0, that always sets the header ``Content-Type: application/json``:

```
res = session.put('http://taskcluster/queue/v1/task/{}'.format(task_id),
                  json=task_def)
```

Otherwise, it looks like [the default](https://github.com/psf/requests/blob/333fa8d3f201f68b82d9e8f26be4987e869fd3bf/requests/models.py#L509-L514) is to omit the header, or maybe use ``application/x-www-form-urlencoded``. It's not clear how either would pass the ``application/json`` test, so it is reasonable to assume this is handled in the proxy. I trust ``requests``, so I doubt it is something bizarre like line feeds in a header being encoded incorrectly.

The code in the proxy is straightforward go, and appears to just copy the headers from the request to the proxied request. There is some code to set some ``X-Taskcluster-Proxy-*`` headers, but not the ``Content-Type``. None of the docs for go's [Request](https://golang.org/pkg/net/http/#Request) imply that they would add this header. It is still possible that the header copying loop is dropping something, but it is hard to see from the code how this would happen.

I'm left wondering how this interaction ever worked. What code injects the ``Content-Type`` header most of the time? I considered that the code that verifies the headers is new, but it has been there a while. The middleware that verifies the header as part of the schema check is about two years old, and the schema itself is also about two years old.

I got side-tracked writing a test for the queue service for ``GET /queue/v1/task/{task_id}`` and an unknown task ID. The code correctly handles this and returns a 404.

I learned a bit about this corner of taskcluster, but I'm afraid I'll have to let others dig deeper to find the issue.

**Comment by djmitche** [comment]
Thanks for the analysis, @jwhitlock -- it seems that at least taskgraph isn't passing the appropriate content-type headers, and quite possibly other users of the proxy have "gotten away with" this behavior.  You've added quite a bit of knowledge to this issue!

The upgrade to taskcluster-proxy was from 5.1.0 to the latest (see 95fffae82786594fdb0f3f141a099b04d57de051).  That's a big jump, and the difference in behavior was stark: works fine with 5.1.0, fails in at least 50/51 cases with 37.1.0.

I set up a 5.1.0 proxy running locally via docker (taskcluster/taskcluster:5.1.0), and called it without an appropriate content-type:
```
lamport ~/tmp $ echo '{"scopes": []}' > payload
lamport ~/tmp $ curl -v -d@payload http://localhost/api/auth/v1/scopes/expand
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 80 (#0)
> POST /api/auth/v1/scopes/expand HTTP/1.1
> Host: localhost
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Length: 14
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 14 out of 14 bytes
< HTTP/1.1 200 OK
< Access-Control-Allow-Headers: X-Requested-With,Content-Type,Authorization,Accept,Origin,Cache-Control
< Access-Control-Allow-Methods: OPTIONS,GET,HEAD,POST,PUT,DELETE,TRACE,CONNECT
< Access-Control-Allow-Origin: *
< Access-Control-Max-Age: 900
< Access-Control-Request-Method: *
< Alt-Svc: clear
< Cache-Control: no-store no-cache must-revalidate
< Content-Length: 18
< Content-Security-Policy: report-uri /__cspreport__;default-src 'none';frame-ancestors 'none';
< Content-Type: application/json; charset=utf-8
< Date: Wed, 30 Sep 2020 15:23:08 GMT
< Etag: W/"12-YHxm3DRYvGHkBZjHlcD1Ad1wZaE"
< Server: openresty
< Strict-Transport-Security: max-age=31536000
< Via: 1.1 google
< X-Content-Type-Options: nosniff
< X-For-Request-Id: a4ced510-ce1b-420d-b001-47a199f50e64
< X-For-Trace-Id: fb22d9f0188f57bd7e4693ac826cd2ad
< X-Taskcluster-Endpoint: https://community-tc.services.mozilla.com/api/auth/v1/scopes/expand
< X-Taskcluster-Proxy-Perm-Clientid: github/28673|djmitche/tcproxy
< X-Taskcluster-Proxy-Revision: c0b39795d5739e682f06bca82581317e65fc3985
< X-Taskcluster-Proxy-Version: 5.1.0
< 
{
  "scopes": []
* Connection #0 to host localhost left intact
}
```
success!  With the v37.1.0 docker image:
```
lamport ~/tmp $curl -v -d@payload http://localhost/api/auth/v1/scopes/expand
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 80 (#0)
> POST /api/auth/v1/scopes/expand HTTP/1.1
> Host: localhost
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Length: 14
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 14 out of 14 bytes
< HTTP/1.1 400 Bad Request
< Access-Control-Allow-Headers: X-Requested-With,Content-Type,Authorization,Accept,Origin,Cache-Control
< Access-Control-Allow-Methods: OPTIONS,GET,HEAD,POST,PUT,DELETE,TRACE,CONNECT
< Access-Control-Allow-Origin: *
< Access-Control-Max-Age: 900
< Access-Control-Request-Method: *
< Alt-Svc: clear
< Cache-Control: no-store no-cache must-revalidate
< Content-Length: 415
< Content-Security-Policy: report-uri /__cspreport__;default-src 'none';frame-ancestors 'none';
< Content-Type: application/json; charset=utf-8
< Date: Wed, 30 Sep 2020 15:24:45 GMT
< Etag: W/"19f-yQLwr37gRCNnZJCFVvh0xzINewc"
< Server: openresty
< Strict-Transport-Security: max-age=31536000
< Via: 1.1 google
< X-Content-Type-Options: nosniff
< X-For-Request-Id: b474a602-67cd-418f-9838-8def204930c9
< X-For-Trace-Id: 6e4cf87e5fcd029a9676207796db7de0
< X-Taskcluster-Endpoint: https://community-tc.services.mozilla.com/api/auth/v1/scopes/expand
< X-Taskcluster-Proxy-Perm-Clientid: github/28673|djmitche/tcproxy
< X-Taskcluster-Proxy-Revision: 
< X-Taskcluster-Proxy-Version: 37.1.0
< 
{
  "code": "MalformedPayload",
  "message": "Payload must be JSON with content-type: application/json got content-type: application/x-www-form-urlencoded\n\n---\n\n* method:     expandScopes\n* errorCode:  MalformedPayload\n* statusCode: 400\n* time:       2020-09-30T15:24:45.104Z",
  "requestInfo": {
    "method": "expandScopes",
    "params": {},
    "payload": {},
    "time": "2020-09-30T15:24:45.104Z"
  }
* Connection #0 to host localhost left intact
}
```

Datapoints:
 * (summarizing above) sending content-type `application/x-www-form-urlencoded` works on 5.1.0, fails on 37.1.0
 * omitting content-type entirely (`curl -v -H "Content-Type:" -d@payload http://localhost/api/auth/v1/scopes/expand`) works on 5.1.0, fails on 37.1.0.
 * sending content-type `text/plain` works on 5.1.0, fails on 37.1.0
 * sending content-type `application/json` works on both

So, something has changed here, and has caused problems.  Chasing down what in the 5.1.0 proxy caused this to work might be interesting, but is probably immaterial.

I agree that the 37.1.0 behavior is "correct", but we are in the uncomfortable position of turning a bug in our users' code from "innocuous" to "showstopper".  This requires some careful consideration.  Options are:
 1. Break it and let users sort it out
 1. Configure 37.1.0 to behave the way 5.1.0 did
 1. Configure 37.1.0 to behave the way 5.1.0 did, but warn about the compatibility behavior with a definite sunset date

#3597 is an implementation of (2), although it misses the first and third datapoints above.

I don't know how to accomplish (3).  @petemoore what do you think?

**Comment by petemoore** [comment]
This is interesting. Until now, I had assumed it was something else adding the header, rather than taskcluster-proxy, since I didn't find anything in the code that was adding it. Since it really seems to be taskcluster-proxy, we do indeed face a dilemma. Let me sleep on this before I commit to an opinion about the best way to proceed. :-/

Thanks for taking the time to manually try taskcluster-proxy 5.1.0 - that was a great idea, and resulted in data that I wasn't expecting.

**Comment by petemoore** [comment]
I found it!

It is [here](https://github.com/taskcluster/taskcluster-proxy/blob/v5.1.0/routes.go#L223) in the old version (5.1.0). That would have called [this line](https://github.com/taskcluster/taskcluster/blob/ea9ceb74f7f3127cad707087579310539ac9cdf1/clients/client-go/http.go#L139) in the go client, since it used the go client for making the requests. This was fixed at some point not to use the client methods, but to sign the original request explicitly (only updating the `Authorization` header) as we see [here](https://github.com/taskcluster/taskcluster/blob/a72c8ca7eeb31c44eb21ba194607f7fbac418592/tools/taskcluster-proxy/routes.go#L239-L243).

So that explains what broke, and gives us a better idea how to make behaviour backwardly compatible, if we decide to do so.

Although it fixes things to do that, it does feel undesirable to manipulate the request's headers in the proxy (which is probably why we changed it), so I'm not sure I'm a huge fan of it staying like this forever. But indeed the obvious solution for now is we make it backwardly compatible, and raise a separate issue that the behaviour is counterintuitive, and at some point would be nice to fix. I guess the last option is documenting the behaviour very well, but that feels less than ideal.

Perhaps we could trace the requests hit the proxy with an incorrect or missing Content-Type and see if we can isolate all the call sites. Perhaps there aren't so many, as there aren't so many tools (presumably) that call the proxy without using an actual taskcluster client that would form the correct headers?

**Comment by djmitche** [comment]
Adding some logging seems like a good idea -- then we can search worker logs for that log message, extract taskIds from it, and look at what created that taskId.  Once we get taskgraph updated (I think there's a Phab Rev for that already?) the remaining instances should be fewer and pretty easy to track down.

**Comment by djmitche** [comment]
This is blocking us updating to a reasonably recent docker-worker in community.  I'll take a crack at it..

**Comment by djmitche** [comment]
OK, with luck, docker-worker and generic-worker v38.0.0 will actually ship with a functional tc-proxy :)

So we can park this for a while.  The [fix to firefox-ci automation](https://phabricator.services.mozilla.com/D92101) has landed, so hopefully the remaining bits are smaller in scope.

**Comment by jwhitlock** [comment]
I opened https://bugzilla.mozilla.org/show_bug.cgi?id=1668585 to coordinate changes in Taskcluster clients. This papertrail query finds the offenders:

https://my.papertrailapp.com/events?focus=1371023453758586882&q=%22Adding+missing+Content-Type+header+%28%233521%29%22

After a recent scan, the only offender was ``docker-worker`` with the prefix ``proj-taskcluster-ci-``. This appears when this repo runs CI tasks. My guess is that the JS client needs updating, but I haven't dug in, and I'll need to pass the baton to the next developer.
