### ISSUE TITLE
GitHub statuses are not reported when `queue:list-task-group:*` is not public

### ISSUE THREAD

**Issue by ricky26** [taskcluster/taskcluster#3830]
**Describe the bug**
GitHub statuses are not reported for tasks when anonymous doesn't have the `queue:list-task-group:*` role.

**To Reproduce**

1. Trigger a build from a repository with a `.taskcluster.yml`.
2. Notice that no status after pending is ever reported.

**Expected behavior**
GitHub statuses should always be posted for GitHub-related tasks.

**Taskcluster version**
v38.0.1

**Additional context**
Error message:
````
"Error: This request requires Taskcluster credentials that satisfy the following scope expression:

```
queue:list-task-group:UZsTpT19Q6W0e1NioEPT4g
```

---

* method:     listTaskGroup
* errorCode:  InsufficientScopes
* statusCode: 403
* time:       2020-11-02T12:50:28.960Z
    at /app/clients/client/src/client.js:403:21
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Handlers.deprecatedStatusHandler (/app/services/github/src/handlers.js:378:19)"
````

I'm happy to PR a bugfix for this, I'll open one soon.

**Comment by ricky26** [comment]
Nevermind, this was fixed in #3822.
