### ISSUE TITLE
e.artifacts is null

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#3839]
**Describe the bug**
Viewing a task gives "e.artifacts is null"

**To Reproduce**

1. Go to https://community-tc.services.mozilla.com/tasks/bOh0SMjqT_uOGdJax_ZKkQ

**Taskcluster version**
38.0.1

Traceback suggests `getLivelogArtifactFromRun` is to blame.

**Comment by petemoore** [comment]
:-(

**Comment by petemoore** [comment]
Is this only while the live log is active? When I follow the link above, I can see the task and its payload and log etc without problems.

**Comment by djmitche** [comment]
I'm still getting the error.  However, I see the task if I'm signed in.

**Comment by djmitche** [comment]
It looks like this is a few layers of ignoring errors.  The [graphql response](https://gist.github.com/djmitche/4ae4d43131ba1b314dcb85a061e550d9) starts with

```json
{
  "errors": [
    {
      "message": "Cannot read property 'status' of undefined",
      "locations": [
        {
          "line": 49,
          "column": 5
        }
      ],
      "path": [
        "task",
        "taskActions"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: Cannot read property 'status' of undefined",
            "    at /home/dustin/p/taskcluster/services/web-server/src/loaders/tasks.js:66:28",
            "    at Array.map (<anonymous>)",
            "    at DataLoader._batchLoadFn (/home/dustin/p/taskcluster/services/web-server/src/loaders/tasks.js:45:15)",
            "    at dispatchBatch (/home/dustin/p/taskcluster/node_modules/dataloader/index.js:275:29)",
            "    at /home/dustin/p/taskcluster/node_modules/dataloader/index.js:258:12",
            "    at processTicksAndRejections (internal/process/task_queues.js:79:11)"
          ]
        }
      }
    },
    {
      "message": "credentials must be given",
      "locations": [
        {
          "line": 41,
          "column": 9
        }
      ],
      "path": [
        "task",
        "status",
        "runs",
        0,
        "artifacts"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: credentials must be given",
            "    at Client._buildSignedUrl (/home/dustin/p/taskcluster/clients/client/src/client.js:642:13)",
            "    at Client.externalBuildSignedUrl (/home/dustin/p/taskcluster/clients/client/src/client.js:677:17)",
            "    at withUrl (/home/dustin/p/taskcluster/services/web-server/src/loaders/artifacts.js:15:17)",
            "    at /home/dustin/p/taskcluster/services/web-server/src/loaders/artifacts.js:46:9",
            "    at Array.map (<anonymous>)",
            "    at /home/dustin/p/taskcluster/services/web-server/src/loaders/artifacts.js:45:38",
            "    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
            "    at async fetch (/home/dustin/p/taskcluster/services/web-server/src/ConnectionLoader.js:10:11)",
            "    at async /home/dustin/p/taskcluster/services/web-server/src/ConnectionLoader.js:31:15",
            "    at async Promise.all (index 0)"
          ]
        }
      }
    }
  ],
  "data": {
...
```

So there are at least two server-side errors, and it seems that the frontend then assumes no error occurs and accesses a nonexistent property, and that causes the cryptic "e.artifacts is null" onscreen.

**Comment by djmitche** [comment]
Neat:
![image](https://user-images.githubusercontent.com/28673/98022918-38e90680-1dd4-11eb-914d-80c18916d9ea.png)
