### ISSUE TITLE
Worker pool is busy despite high maxCapacity

### ISSUE THREAD

**Issue by jschwartzentruber** [taskcluster/taskcluster#4125]
**Describe the bug**

I have a periodic hook that fires 16 tasks every 6 hours, with a deadline of 6 hours (to run continuously). Including the decision, I expect the maximum tasks required to be 17, but setting the `maxCapacity` to 17 results in tasks remaining pending until they hit their deadline and raise an exception. I have tried doubling the `maxCapacity` to 33, and I still see pending tasks.

**To Reproduce**

The hook in question is here:
https://community-tc.services.mozilla.com/hooks/project-fuzzing/linux-pool8

... and the worker pool has the same name:
https://community-tc.services.mozilla.com/worker-manager/proj-fuzzing%2Flinux-pool8

**Expected behavior**

Worker pool with `maxCapacity` should be able to run that many tasks simultaneously.

**Taskcluster version**

39.1.1-6-g65facdf39

**Screenshots**

![image](https://user-images.githubusercontent.com/4673461/102413482-ff0a4300-3fc2-11eb-87d3-305f5aa7f99a.png)
(although it can't be shown, there are no other tasks in the running state in that pool, observed in prior task groups and in the provisioner worker view).

**Platform (please complete the following information):**

 - docker-worker (Linux)
 
**Additional context**

This could very well be a misconfiguration in the pool that I'm not seeing.

**Comment by imbstack** [comment]
Appears that docker-worker is crashing which means that the worker doesn't terminate itself. I think there are going to be 2 fixes, one quick workaround for fuzzing and one that is just figuring out what is going on here. I'll have more in a bit.

```
Dec 20 10:34:02 proj-fuzzing-linux-pool8-rfjv29eqq-6uqhrm-crmbq docker-worker: Unhandled rejection at [object Promise].
Dec 20 10:34:02 proj-fuzzing-linux-pool8-rfjv29eqq-6uqhrm-crmbq docker-worker: Error: (HTTP code 409) unexpected - Cannot kill container: b5c559f2ea9b6db1f21a6f2e776e5db4f9b2a99cc94a85fcfd5a04adf73e2440: Container b5c559f2ea9b6db1f21a6f2e776e5db4f9b2a99cc94a85fcfd5a04adf73e2440 is not running
Dec 20 10:34:02 proj-fuzzing-linux-pool8-rfjv29eqq-6uqhrm-crmbq docker-worker:     at /home/ubuntu/docker-worker/node_modules/docker-modem/lib/modem.js:301:17
Dec 20 10:34:02 proj-fuzzing-linux-pool8-rfjv29eqq-6uqhrm-crmbq docker-worker:     at getCause (/home/ubuntu/docker-worker/node_modules/docker-modem/lib/modem.js:331:7)
Dec 20 10:34:02 proj-fuzzing-linux-pool8-rfjv29eqq-6uqhrm-crmbq docker-worker:     at Modem.buildPayload (/home/ubuntu/docker-worker/node_modules/docker-modem/lib/modem.js:300:5)
Dec 20 10:34:02 proj-fuzzing-linux-pool8-rfjv29eqq-6uqhrm-crmbq docker-worker:     at IncomingMessage.<anonymous> (/home/ubuntu/docker-worker/node_modules/docker-modem/lib/modem.js:275:14)
Dec 20 10:34:02 proj-fuzzing-linux-pool8-rfjv29eqq-6uqhrm-crmbq docker-worker:     at IncomingMessage.emit (events.js:326:22)
Dec 20 10:34:02 proj-fuzzing-linux-pool8-rfjv29eqq-6uqhrm-crmbq docker-worker:     at IncomingMessage.EventEmitter.emit (domain.js:483:12)
Dec 20 10:34:02 proj-fuzzing-linux-pool8-rfjv29eqq-6uqhrm-crmbq docker-worker:     at endReadableNT (_stream_readable.js:1223:12)
Dec 20 10:34:02 proj-fuzzing-linux-pool8-rfjv29eqq-6uqhrm-crmbq docker-worker:     at processTicksAndRejections (internal/process/task_queues.js:84:21)
Dec 20 10:34:02 proj-fuzzing-linux-pool8-rfjv29eqq-6uqhrm-crmbq docker-worker: 2020/12/20 18:20:45 {"EnvVersion":"2.0","Fields":{"json":{"message":"Cannot kill container: b5c559f2ea9b6db1f21a6f2e776e5db4f9b2a99cc94a85fcfd5a04adf73e2440: Container b5c559f2ea9b6db1f21a6f2e776e5db4f9b2a99cc94a85fcfd5a04adf73e2440 is not running"},"message":"(HTTP code 409) unexpected - Cannot kill container: b5c559f2ea9b6db1f21a6f2e776e5db4f9b2a99cc94a85fcfd5a04adf73e2440: Container b5c559f2ea9b6db1f21a6f2e776e5db4f9b2a99cc94a85fcfd5a04adf73e2440 is not running ","name":"Error","stack":"Error: (HTTP code 409) unexpected - Cannot kill container: b5c559f2ea9b6db1f21a6f2e776e5db4f9b2a99cc94a85fcfd5a04adf73e2440: Container b5c559f2ea9b6db1f21a6f2e776e5db4f9b2a99cc94a85fcfd5a04adf73e2440 is not running \n    at /home/ubuntu/docker-worker/node_modules/docker-modem/lib/modem.js:301:17\n    at getCause (/home/ubuntu/docker-worker/node_modules/docker-modem/lib/modem.js:331:7)\n    at Modem.buildPayload (/home/ubuntu/docker-worker/node_modules/docker-modem/lib/modem.js:300:5)\n
Dec 20 10:34:02 proj-fuzzing-linux-pool8-rfjv29eqq-6uqhrm-crmbq docker-worker: at IncomingMessage.<anonymous> (/home/ubuntu/docker-worker/node_modules/docker-modem/lib/modem.js:275:14)\n    at IncomingMessage.emit (events.js:326:22)\n    at IncomingMessage.EventEmitter.emit (domain.js:483:12)\n    at endReadableNT (_stream_readable.js:1223:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)","statusCode":409,"v":1},"Hostname":"proj-fuzzing-linux-pool8-rfjv29eqq-6uqhrm-crmbq","Logger":"taskcluster.docker-worker","Pid":2550,"Severity":3,"Timestamp":1608488445746000000,"Type":"monitor.error","message":"Error: (HTTP code 409) unexpected - Cannot kill container: b5c559f2ea9b6db1f21a6f2e776e5db4f9b2a99cc94a85fcfd5a04adf73e2440: Container b5c559f2ea9b6db1f21a6f2e776e5db4f9b2a99cc94a85fcfd5a04adf73e2440 is not running \n    at /home/ubuntu/docker-worker/node_modules/docker-modem/lib/modem.js:301:17\n    at getCause (/home/ubuntu/docker-worker/node_modules/docker-modem/lib/modem.js:331:7)\n    at Modem.buildPayload (/home/ubuntu/docker
Dec 20 10:34:02 proj-fuzzing-linux-pool8-rfjv29eqq-6uqhrm-crmbq docker-worker: -worker/node_modules/docker-modem/lib/modem.js:300:5)\n    at IncomingMessage.<anonymous> (/home/ubuntu/docker-worker/node_modules/docker-modem/lib/modem.js:275:14)\n    at IncomingMessage.emit (events.js:326:22)\n    at IncomingMessage.EventEmitter.emit (domain.js:483:12)\n    at endReadableNT (_stream_readable.js:1223:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)","serviceContext":{"service":"docker-worker","version":"38.0.5"},"severity":"ERROR"}
Dec 20 10:34:02 proj-fuzzing-linux-pool8-rfjv29eqq-6uqhrm-crmbq docker-worker: 2020/12/20 18:20:45 exit status 1 
```

**Comment by imbstack** [comment]
@jschwartzentruber I believe that you configure the `fuzzing-linux` pools yourself. We think that the quickest fix for you will be setting `lifecycle.reregistrationTimeout` to an hour or so (docs are [here](https://docs.taskcluster.net/docs/reference/core/worker-manager/google)). As far as I can tell, only fuzzing pools are failing this way. I'm not sure why that would be quite yet.

This fix will make it so that workers quickly are terminated after a crash but won't stop the crash itself. Hopefully we can make some progress on that but it probably won't be fixed before the break at this rate.

**Comment by jschwartzentruber** [comment]
> @jschwartzentruber I believe that you configure the `fuzzing-linux` pools yourself. We think that the quickest fix for you will be setting `lifecycle.reregistrationTimeout` to an hour or so (docs are [here](https://docs.taskcluster.net/docs/reference/core/worker-manager/google)). As far as I can tell, only fuzzing pools are failing this way. I'm not sure why that would be quite yet.
> 
> This fix will make it so that workers quickly are terminated after a crash but won't stop the crash itself. Hopefully we can make some progress on that but it probably won't be fixed before the break at this rate.

Should this be maxRunTime + 1hr ? I see a lot of exceptions since making this change (reason: worker_shutdown). eg. https://community-tc.services.mozilla.com/tasks/groups/MCr_KdswQfqn3nkfGIYnMw

**Comment by imbstack** [comment]
No, that should've just worked. I would roll it back and we'll investigate that now too. Sorry, this is not a good look for us so far!

**Comment by imbstack** [comment]
```

Dec 23 08:29:21 proj-fuzzing-linux-pool8-dcnn2fvqr162jsajlcko6a docker-worker: 2020/12/23 16:29:21 Taskcluster Credentials are expiring in 30m0s; re-registering
Dec 23 08:29:21 proj-fuzzing-linux-pool8-dcnn2fvqr162jsajlcko6a docker-worker: 2020/12/23 16:29:21 Error: (Intermittent) HTTP response code 500
Dec 23 08:29:21 proj-fuzzing-linux-pool8-dcnn2fvqr162jsajlcko6a docker-worker: HTTP/2.0 500 Internal Server Error
Dec 23 08:29:21 proj-fuzzing-linux-pool8-dcnn2fvqr162jsajlcko6a docker-worker: Content-Length: 584
Dec 23 08:29:21 proj-fuzzing-linux-pool8-dcnn2fvqr162jsajlcko6a docker-worker: Access-Control-Allow-Headers: X-Requested-With,Content-Type,Authorization,Accept,Origin,Cache-Control
Dec 23 08:29:21 proj-fuzzing-linux-pool8-dcnn2fvqr162jsajlcko6a docker-worker: Access-Control-Allow-Methods: OPTIONS,GET,HEAD,POST,PUT,DELETE,TRACE,CONNECT
Dec 23 08:29:21 proj-fuzzing-linux-pool8-dcnn2fvqr162jsajlcko6a docker-worker: Access-Control-Allow-Origin: *
Dec 23 08:29:21 proj-fuzzing-linux-pool8-dcnn2fvqr162jsajlcko6a docker-worker: Access-Control-Max-Age: 900
Dec 23 08:29:21 proj-fuzzing-linux-pool8-dcnn2fvqr162jsajlcko6a docker-worker: Access-Control-Request-Method: *
Dec 23 08:29:21 proj-fuzzing-linux-pool8-dcnn2fvqr162jsajlcko6a docker-worker: Alt-Svc: clear
Dec 23 08:29:21 proj-fuzzing-linux-pool8-dcnn2fvqr162jsajlcko6a docker-worker: Cache-Control: no-store no-cache must-revalidate
Dec 23 08:29:21 proj-fuzzing-linux-pool8-dcnn2fvqr162jsajlcko6a docker-worker: Content-Security-Policy: report-uri /__cspreport__;default-src 'none';frame-ancestors 'none';
Dec 23 08:29:21 proj-fuzzing-linux-pool8-dcnn2fvqr162jsajlcko6a docker-worker: Content-Type: application/json; charset=utf-8
Dec 23 08:29:21 proj-fuzzing-linux-pool8-dcnn2fvqr162jsajlcko6a docker-worker: Date: Wed, 23 Dec 2020 16:29:21 GMT
Dec 23 08:29:21 proj-fuzzing-linux-pool8-dcnn2fvqr162jsajlcko6a docker-worker: Etag: W/"248-1fKFsSXMjexLnMkYJws2yd7HMB0"
Dec 23 08:29:21 proj-fuzzing-linux-pool8-dcnn2fvqr162jsajlcko6a docker-worker: Server: openresty
Dec 23 08:29:21 proj-fuzzing-linux-pool8-dcnn2fvqr162jsajlcko6a docker-worker: Strict-Transport-Security: max-age=31536000
Dec 23 08:29:21 proj-fuzzing-linux-pool8-dcnn2fvqr162jsajlcko6a docker-worker: Via: 1.1 google
Dec 23 08:29:21 proj-fuzzing-linux-pool8-dcnn2fvqr162jsajlcko6a docker-worker: X-Content-Type-Options: nosniff
Dec 23 08:29:21 proj-fuzzing-linux-pool8-dcnn2fvqr162jsajlcko6a docker-worker: X-For-Request-Id: a50020b9-2032-4b7c-8cf0-1acaa34bd1ae
Dec 23 08:29:21 proj-fuzzing-linux-pool8-dcnn2fvqr162jsajlcko6a docker-worker: X-For-Trace-Id: 6ab681b3133d2d0bb3ea0ec0e600c59b
Dec 23 08:29:21 proj-fuzzing-linux-pool8-dcnn2fvqr162jsajlcko6a docker-worker: {
Dec 23 08:29:21 proj-fuzzing-linux-pool8-dcnn2fvqr162jsajlcko6a docker-worker:   "code": "InternalServerError",
Dec 23 08:29:21 proj-fuzzing-linux-pool8-dcnn2fvqr162jsajlcko6a docker-worker:   "message": "Internal Server Error, incidentId 072bf60d-872c-4058-91aa-685c41a0b444.\n\n---\n\n* method:     reregisterWorker\n* errorCode:  InternalServerError\n* statusCode: 500\n* time:       2020-12-23T16:29:21.429Z",
Dec 23 08:29:21 proj-fuzzing-linux-pool8-dcnn2fvqr162jsajlcko6a docker-worker:   "requestInfo": {
Dec 23 08:29:21 proj-fuzzing-linux-pool8-dcnn2fvqr162jsajlcko6a docker-worker:     "method": "reregisterWorker",
Dec 23 08:29:21 proj-fuzzing-linux-pool8-dcnn2fvqr162jsajlcko6a docker-worker:     "params": {},
Dec 23 08:29:21 proj-fuzzing-linux-pool8-dcnn2fvqr162jsajlcko6a docker-worker:     "payload": {
Dec 23 08:29:21 proj-fuzzing-linux-pool8-dcnn2fvqr162jsajlcko6a docker-worker:       "secret": "********************************",
Dec 23 08:29:21 proj-fuzzing-linux-pool8-dcnn2fvqr162jsajlcko6a docker-worker:       "workerGroup": "us-east4",
Dec 23 08:29:21 proj-fuzzing-linux-pool8-dcnn2fvqr162jsajlcko6a docker-worker:       "workerId": "7307473890912950213",
Dec 23 08:29:21 proj-fuzzing-linux-pool8-dcnn2fvqr162jsajlcko6a docker-worker:       "workerPoolId": "proj-fuzzing/linux-pool8"
Dec 23 08:29:21 proj-fuzzing-linux-pool8-dcnn2fvqr162jsajlcko6a docker-worker:     },
Dec 23 08:29:21 proj-fuzzing-linux-pool8-dcnn2fvqr162jsajlcko6a docker-worker:     "time": "2020-12-23T16:29:21.429Z"
Dec 23 08:29:21 proj-fuzzing-linux-pool8-dcnn2fvqr162jsajlcko6a docker-worker:   } 
```

**Comment by imbstack** [comment]
And indeed, in the worker-manager logs we have for that `requestId`:

```
AssertionError [ERR_ASSERTION]: Credentials cannot span more than 31 days
    at Object.exports.createTemporaryCredentials (/app/clients/client/src/client.js:767:3)
    at createCredentials (/app/services/worker-manager/src/util.js:34:22)
    at Proxy.<anonymous> (/app/services/worker-manager/src/api.js:785:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by imbstack** [comment]
@jschwartzentruber while we're working on the longer-term fixes, we also believe that you can set reregistration timeout to `3` (roughly 3600 / 1000) to get the desired effect for now. It might or might not work but we're not going to get this deployed until the new year at this rate.
