### ISSUE TITLE
debugging issues with the loader stinks

### ISSUE THREAD

**Issue by jhford** [taskcluster/taskcluster#47]
Example: We have a cycle, we know that, but the way that we're checking for cycles makes it impossible to determine where the cycle is without manually tracing it.  We also can't run the graphviz generator target to see where the cycle is because we do the cycle check first.

Two things:
1. this error message ought to say what the cycle is
2. we should be able to generate a graphviz dot file that shows the cycle

```
/Users/jhford/taskcluster/cloud-mirror/node_modules/topo-sort/tsort.js:88
    throw new Error('At least 1 circular dependency in nodes: \n\n' + circular.join('\n') + '\n\nGraph cannot be sorted!');
          ^
Error: At least 1 circular dependency in nodes:

cfg
profile
redis
sqs
monitor
process
validator
api
registeredCacheManagers
server
queueUrl
queue
cacheManagers

Graph cannot be sorted!
    at [object Object].TopoSort.sort (/Users/jhford/taskcluster/cloud-mirror/node_modules/topo-sort/tsort.js:88:11)
    at Object.loader (/Users/jhford/taskcluster/cloud-mirror/node_modules/taskcluster-lib-loader/src/loader.js:161:26)
    at Object.<anonymous> (/Users/jhford/taskcluster/cloud-mirror/src/main.js:61:8)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3
```

**Comment by djmitche** [comment]
@jhford is this still worth keeping as an open issue?

**Comment by djmitche** [comment]
I haven't seen a circular reference in the loader, so I think this is OK for now.
