### ISSUE TITLE
worker-manager cert tests failing

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#4744]
worker-manager tests are failing:
```
  1) services/worker-manager/test/provider_azure_test.js
       registerWorker
         pre-IDd
           bad cert:
      AssertionError [ERR_ASSERTION]: 'Error reading intermediate certificate' == 'Error verifying new intermediate certificate'
      + expected - actual
      -Error reading intermediate certificate
      +Error verifying new intermediate certificate
      
      at Context.<anonymous> (test/provider_azure_test.js:1377:18)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  2) services/worker-manager/test/provider_azure_test.js
       registerWorker
         pre-IDd
           success after downloading missing intermediate:
     Error: Signature validation error
      at error (src/providers/azure.js:436:25)
      at AzureProvider.registerWorker (src/providers/azure.js:559:15)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async Context.<anonymous> (test/provider_azure_test.js:1497:23)

  3) services/worker-manager/test/provider_azure_test.js
       registerWorker
         fetch-in-register
           bad cert:
      AssertionError [ERR_ASSERTION]: 'Error reading intermediate certificate' == 'Error verifying new intermediate certificate'
      + expected - actual
      -Error reading intermediate certificate
      +Error verifying new intermediate certificate
      
      at Context.<anonymous> (test/provider_azure_test.js:1377:18)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
  4) services/worker-manager/test/provider_azure_test.js
       registerWorker
         fetch-in-register
           success after downloading missing intermediate:
     Error: Signature validation error
      at error (src/providers/azure.js:436:25)
      at AzureProvider.registerWorker (src/providers/azure.js:559:15)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async Context.<anonymous> (test/provider_azure_test.js:1497:23)
```

starting at least 4h ago.  At a guess, something expired at the start of April 9 UTC.

**Comment by djmitche** [comment]
In the service logs (via debug logs):
```
  taskcluster.test.azure WARNING: registration-error-warning: Error reading intermediate certificate
  taskcluster.test.azure        error: Error: Too few bytes to parse DER.; location=http://www.microsoft.com/pki/mscorp/Microsoft%20IT%20TLS%20CA%204.crt                                                                                                        
  taskcluster.test.azure        message: Error reading intermediate certificate              
  taskcluster.test.azure        v: 1 +0ms                                       
  taskcluster.test.azure WARNING: registration-error-warning: Unable to download intermediate certificate
  taskcluster.test.azure        error: Certificate "/C=US,/ST=Washington,/L=Redmond,/O=Microsoft Corporation,/OU=Microsoft IT,/CN=Microsoft IT TLS CA 4"; AuthorityAccessInfo [{"method":"CA Issuer","location":"http://www.microsoft.com/pki/mscorp/Microsoft%20IT%20TLS%20CA%204.crt"},{"method":"OSCP","location":"http://ocsp.msocsp.com"}]                                                                                                                                                                                    
  taskcluster.test.azure        message: Unable to download intermediate certificate
  taskcluster.test.azure        v: 1 +0ms                                             
```

I wonder if we'll see this in production too..

**Comment by petemoore** [comment]
```
$ curl -L http://www.microsoft.com/pki/mscorp/Microsoft%20IT%20TLS%20CA%204.crt > crt && openssl x509 -in crt -out cert.pem; rm crt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1464  100  1464    0     0  35707      0 --:--:-- --:--:-- --:--:-- 35707
unable to load certificate
4669398700:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:708:Expecting: TRUSTED CERTIFICATE
```

**Comment by petemoore** [comment]
@djmitche Maybe related to #3638?

**Comment by petemoore** [comment]
@djmitche I'm not sure why this issue got assigned to me - it is end of my day here. Is there anyone else that can take it?

**Comment by djmitche** [comment]
I think you've made the most progress.  At the moment it can wait until Monday.

**Comment by djmitche** [comment]
I tried to bisect this, but it fails all the way back to at least 727cb095bb7eff738c5cca9d743679c6081e7937 (March 29), which is quite a bit before we started seeing this failure in CI.

**Comment by djmitche** [comment]
Setting my system time back (https://www.systutorials.com/docs/linux/man/1-faketime/) also doesn't help, so it would seem this is related to something changing at http://www.microsoft.com/pki/mscorp/Microsoft%20IT%20TLS%20CA%204.crt

**Comment by djmitche** [comment]
In the response headers from that URL:

    'last-modified': 'Thu, 08 Apr 2021 20:38:24 GMT',

that lines up pretty well!

**Comment by djmitche** [comment]
This is happening again.  WTF Azure.

**Comment by djmitche** [comment]
http://www.microsoft.com/pki/mscorp/Microsoft%20IT%20TLS%20CA%204.crt is now a 403.

**Comment by djmitche** [comment]
I think that's a funny way of spelling 404 (much like S3!).  Even loading in a browser gives 

> Your request has been blocked. This may be due to several reasons.
> 1. You are using a proxy that is known to send automated requests to Microsoft. Check with your network administrator if there is any proxy and what User-Agent they are sending in the request header.
> 2. Your request pattern matches an automated process. To eliminate, reduce the volume of requests over a period of time.
> 3. Reference ID: 18.54bc7768.1618929745.219d69b1

**Comment by djmitche** [comment]
https://www.microsoft.com/pki/mscorp/cps/default.htm now only lists two certs
