### ISSUE TITLE
Entity too large can cause us to silently error

### ISSUE THREAD

**Issue by imbstack** [taskcluster/taskcluster#48]
getsentry/raven-node#153 affects us. I just saw it in tc-gh

```

Feb 16 13:33:55 taskcluster-github app/web.1:   * data.builds[997] should have required property 'eventId' 
Feb 16 13:33:55 taskcluster-github app/web.1:     at ServerResponse.res.reply (/app/node_modules/taskcluster-lib-api/lib/api.js:144:21) 
Feb 16 13:33:55 taskcluster-github app/web.1:     at Object._callee2$ (/app/lib/api.js:368:51) 
Feb 16 13:33:55 taskcluster-github app/web.1:     at tryCatch (/app/node_modules/regenerator-runtime/runtime.js:62:40) 
Feb 16 13:33:55 taskcluster-github app/web.1:     at GeneratorFunctionPrototype.invoke [as _invoke] (/app/node_modules/regenerator-runtime/runtime.js:336:22) 
Feb 16 13:33:55 taskcluster-github app/web.1:     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/app/node_modules/regenerator-runtime/runtime.js:95:21) 
Feb 16 13:33:55 taskcluster-github app/web.1:     at step (/app/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30) 
Feb 16 13:33:55 taskcluster-github app/web.1:     at /app/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:20 
Feb 16 13:33:55 taskcluster-github app/web.1:     at process._tickDomainCallback (internal/process/next_tick.js:129:7) 
Feb 16 13:33:55 taskcluster-github app/web.1: Failed to log error to Sentry: Error: HTTP Error (413): undefined 
```

The exception was indeed quite a long list of validation errors. We should probably handle this case intelligently.

**Comment by imbstack** [comment]
This will all go away with structured logging stuff so I'm closing.
