### ISSUE TITLE
Deadlock when trying to run the windows runner

### ISSUE THREAD

**Issue by Eijebong** [taskcluster/taskcluster#5007]
Hey, I'm getting deadlocks when trying to run the windows runner in a virtual machine.

Machine is windows 10, up to date, nothing specific specific installed on it (default + firefox and spice-vdagent).

Here are the config files and logs:

start-worker.yml
```
provider:
  providerType: static
  providerID: static
  workerPoolID: project/windows
  workerGroup: ci
  workerID: windows-2
  staticSecret: nope
  rootURL: nope

worker:
  implementation: generic-worker
  service: "Generic Worker"
  configPath: c:\generic-worker\generic-worker-config.yml
  protocolPipe: \\.\pipe\generic-worker

workerConfig:
  ed25519SigningKeyLocation: ./key.private
```

generic-worker.yml
```
{
  "accessToken": "nope",
  "certificate": "{\"version\":1,\"scopes\":[\"assume:worker-type:project/windows\",\"assume:worker-pool:project/windows\",\"assume:worker-id:ci/windows-2\",\"queue:worker-id:ci/windows-2\",\"secrets:get:worker-type:project/windows\",\"secrets:get:worker-pool:project/windows\",\"queue:claim-work:project/windows\",\"worker-manager:remove-worker:project/windows/ci/windows-2\",\"worker-manager:reregister-worker:project/windows/ci/windows-2\"],\"start\":1636453317168,\"expiry\":1636799816343,\"seed\":\"pouet\",\"signature\":\"baguette\",\"issuer\":\"static/taskcluster/worker-manager\"}",
  "clientId": "worker/static/project/windows/ci/windows-2",
  "ed25519SigningKeyLocation": "./key.private",
  "provisionerId": "project",
  "rootURL": "nope",
  "workerGroup": "ci",
  "workerId": "windows-2",
  "workerType": "windows",
  "workerTypeMetadata": {}
}
```

start-worker.log
```
2021/11/09 12:18:55 Loading worker-runner configuration from .\generic-worker-config.yml
2021/11/09 12:18:55 Configuring with provider static
2021/11/09 12:18:57 Identified as worker ci/windows-2
2021/11/09 12:18:57 Getting secrets from secrets service
2021/11/09 12:18:58 WARNING: No worker secrets for worker pool project/windows.
2021/11/09 12:18:58 Configuring for worker implementation generic-worker
2021/11/09 12:18:58 provider metadata instance-id not available; not setting config instanceID
2021/11/09 12:18:58 provider metadata region not available; not setting config region
2021/11/09 12:18:58 provider metadata availability-zone not available; not setting config availabilityZone
2021/11/09 12:18:58 provider metadata public-ipv4 not available; not setting config publicIp
2021/11/09 12:18:58 provider metadata local-ipv4 not available; not setting config privateIP
2021/11/09 12:18:58 provider metadata instance-type not available; not setting config instanceType
2021/11/09 12:18:58 Writing files
2021/11/09 12:18:58 Starting worker
2021/11/09 12:18:58 Worker credentials expire in 95h59m59s
2021/11/09 12:18:58 Worker connecteed on protocolPipe
```

worker.log
```
2021/11/09 11:18:58Z Making system call GetProfilesDirectoryW with args: [C00012CF70 C0003CE5F8]
2021/11/09 11:18:58Z   Result: 1 0 The operation completed successfully.
```

Sometimes I'm getting `fatal error: all goroutines are asleep - deadlock` in that log file too.
One time I got:

```
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [semacquire]:
sync.runtime_SemacquireMutex(0xc000056054, 0x1000000009cde00, 0x1)
	/task_161462437854361/go/go/src/runtime/sema.go:71 +0x4e
sync.(*Mutex).lockSlow(0xc000056050)
	/task_161462437854361/go/go/src/sync/mutex.go:138 +0x10f
sync.(*Mutex).Lock(...)
	/task_161462437854361/go/go/src/sync/mutex.go:81
log.(*Logger).Output(0xc000056050, 0x2, 0xc0003fc360, 0x5a, 0x0, 0x0)
	/task_161462437854361/go/go/src/log/log.go:162 +0x41c
log.Printf(0x103b1bf, 0x24, 0xc00019fa80, 0x1, 0x1)
	/task_161462437854361/go/go/src/log/log.go:320 +0x87
github.com/taskcluster/taskcluster/v42/tools/workerproto.(*PipeTransport).Send(0xc00036d5c0, 0x1025574, 0x3, 0xc000086000)
	/task_161462437854361/taskcluster/tools/workerproto/pipe.go:47 +0x21e
github.com/taskcluster/taskcluster/v42/tools/workerproto.(*Protocol).Send(...)
	/task_161462437854361/taskcluster/tools/workerproto/protocol.go:154
main.(*loggingWriter).Write(0xc0000068d8, 0xc0003aecd0, 0x4c, 0x50, 0x14523e0, 0x0, 0x0)
	/task_161462437854361/taskcluster/workers/generic-worker/workerrunner.go:37 +0x202
log.(*Logger).Output(0xc000056050, 0x2, 0xc0003aedc0, 0x4b, 0x0, 0x0)
	/task_161462437854361/go/go/src/log/log.go:181 +0x294
log.Printf(0x103a1bc, 0x23, 0xc00019fc98, 0x2, 0x2)
	/task_161462437854361/go/go/src/log/log.go:320 +0x87
github.com/taskcluster/taskcluster/v42/workers/generic-worker/win32.(*LazyProcWrapper).Call(0xc0000060c0, 0xc0003cf2d0, 0x2, 0x2, 0xc00019fd48, 0xa0c918, 0xd0, 0xf5df60)
	/task_161462437854361/taskcluster/workers/generic-worker/win32/wrap_dll_windows.go:33 +0xf1
github.com/taskcluster/taskcluster/v42/workers/generic-worker/win32.GetProfilesDirectory(0xc00012d1e0, 0xc0003cf2c8, 0x64, 0xc00012d1e0)
	/task_161462437854361/taskcluster/workers/generic-worker/win32/win32_windows.go:456 +0x89
github.com/taskcluster/taskcluster/v42/workers/generic-worker/win32.ProfilesDirectory(0x22ec93fbff8, 0x8)
	/task_161462437854361/taskcluster/workers/generic-worker/win32/win32_windows.go:495 +0x95
main.defaultTasksDir(...)
	/task_161462437854361/taskcluster/workers/generic-worker/multiuser_windows.go:371
main.loadConfig(0xc00040aef0, 0xc00040aef0, 0x0)
	/task_161462437854361/taskcluster/workers/generic-worker/main.go:220 +0x3b
main.main()
	/task_161462437854361/taskcluster/workers/generic-worker/main.go:144 +0x6ee
```

This happens with both the latest version and 32.0.0

**Comment by Eijebong** [comment]
Full windows version: Windows 10 Pro 21H1 build 19043.1320
