### ISSUE TITLE
Drop support for Python-2.7

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster#5015]
It looks like the dependencies of the py27 client no longer build.  I think we've waited long enough beyond the EOL of Python-2.7 now, and can just drop it.

**Comment by djmitche** [comment]
https://community-tc.services.mozilla.com/tasks/Hvs9T0t6Qte_q6EZDuA4kA/runs/0/logs/public/logs/live.log
```
Collecting lazy-object-proxy
  Downloading lazy-object-proxy-1.7.0.tar.gz (42 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /taskcluster/clients/client-py/.tox/py27/bin/python /taskcluster/clients/client-py/.tox/py27/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpTgKV2J
         cwd: /tmp/pip-install-eb1pMc/lazy-object-proxy
    Complete output (46 lines):
    running dist_info
    creating /tmp/pip-modern-metadata-9Sjryt/lazy_object_proxy.egg-info
    writing dependency_links to /tmp/pip-modern-metadata-9Sjryt/lazy_object_proxy.egg-info/dependency_links.txt
    writing /tmp/pip-modern-metadata-9Sjryt/lazy_object_proxy.egg-info/PKG-INFO
    writing top-level names to /tmp/pip-modern-metadata-9Sjryt/lazy_object_proxy.egg-info/top_level.txt
    writing manifest file '/tmp/pip-modern-metadata-9Sjryt/lazy_object_proxy.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "/taskcluster/clients/client-py/.tox/py27/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/taskcluster/clients/client-py/.tox/py27/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/taskcluster/clients/client-py/.tox/py27/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/tmp/pip-build-env-NQwFE9/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 156, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/tmp/pip-build-env-NQwFE9/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 243, in run_setup
        self).run_setup(setup_script=setup_script)
      File "/tmp/pip-build-env-NQwFE9/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 142, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 146, in <module>
        distclass=BinaryDistribution,
      File "/tmp/pip-build-env-NQwFE9/overlay/lib/python2.7/site-packages/setuptools/__init__.py", line 162, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/local/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-env-NQwFE9/overlay/lib/python2.7/site-packages/setuptools/command/dist_info.py", line 31, in run
        egg_info.run()
      File "/tmp/pip-build-env-NQwFE9/overlay/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 296, in run
        self.find_sources()
      File "/tmp/pip-build-env-NQwFE9/overlay/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 303, in find_sources
        mm.run()
      File "/tmp/pip-build-env-NQwFE9/overlay/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 534, in run
        self.add_defaults()
      File "/tmp/pip-build-env-NQwFE9/overlay/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 570, in add_defaults
        sdist.add_defaults(self)
      File "/tmp/pip-build-env-NQwFE9/overlay/lib/python2.7/site-packages/setuptools/command/py36compat.py", line 36, in add_defaults
        self._add_defaults_ext()
      File "/tmp/pip-build-env-NQwFE9/overlay/lib/python2.7/site-packages/setuptools/command/py36compat.py", line 118, in _add_defaults_ext
        if self.distribution.has_ext_modules():
      File "setup.py", line 70, in has_ext_modules
        return super().has_ext_modules() or 'SETUP_PY_ALLOW_PURE' not in os.environ
    TypeError: super() takes at least 1 argument (0 given)
    ----------------------------------------
ERROR: Command errored out with exit status 1: /taskcluster/clients/client-py/.tox/py27/bin/python /taskcluster/clients/client-py/.tox/py27/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpTgKV2J Check the logs for full command output.
```

**Comment by djmitche** [comment]
Hah, well, [it turns out](https://github.com/ionelmc/python-lazy-object-proxy/issues/61#issuecomment-994787889) this particular issue has been fixed.  But, this is probably still a good idea.

**Comment by djmitche** [comment]
Dup #4614.
