### ISSUE TITLE
[client-shell] panic with`taskcluster task status <id>` on an unscheduled task

### ISSUE THREAD

**Issue by ahal** [taskcluster/taskcluster#5208]
**Describe the bug**
A runtime panic occurs if running `taskcluster task status` with a task that is unscheduled (or invalid)

**To Reproduce**

1. Find an unscheduled task
2. 
```
$ taskcluster task status YuR8AkfJSq6y6Li13aGT7g
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
github.com/taskcluster/taskcluster/v44/clients/client-shell/cmds/task.runStatus(0x0, {0xc00028da80, 0x1, 0xc00031fdb8}, {0x93a1e0, 0xc00019a008}, 0xc00029b700)
        /task_164389933991582/taskcluster/clients/client-shell/cmds/task/fetchers.go:55 +0x425
github.com/taskcluster/taskcluster/v44/clients/client-shell/cmds/task.executeHelperE.func1(0xc20920, {0xc00028da80, 0x1, 0x1})
        /task_164389933991582/taskcluster/clients/client-shell/cmds/task/utils.go:35 +0x1e3
github.com/spf13/cobra.(*Command).execute(0xc20920, {0xc00028da50, 0x1, 0x1})
        /task_164389933991582/go/path/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001b6280)
        /task_164389933991582/go/path/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
        /task_164389933991582/go/path/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
        /task_164389933991582/taskcluster/clients/client-shell/main.go:15 +0x25
```

**Expected behavior**
The client binary should at least handle this gracefully and print an error message. Bonus points if it figures out whether the task is invalid, or just `unscheduled` and print `unscheduled` in the latter case.

**Taskcluster version**
44.5.0

**Comment by Eijebong** [comment]
```
> ./client-shell task status KhdlmUReSxm-tDOn2jCw6Q
Error: task has no runs
```

This was fixed by #8375
