### ISSUE TITLE
Windows multiuser worker panics because accounts got in a wrong state

### ISSUE THREAD

**Issue by Eijebong** [taskcluster/taskcluster#5270]
No idea what happened here, had that in my logs.

```
2022/03/08 11:03:39Z Could not persist features: exit status 1352
2022/03/08 11:03:39Z Running command: icacls 'tasks-resolved-count.txt' /grant:r 'Administrators:(GA)' /inheritance:r
2022/03/08 11:03:39Z Error running command:
2022/03/08 11:03:39Z Administrators: The security account manager (SAM) or local security authority (LSA) server was in the wrong state to perform the security operation.
Successfully processed 0 files; Failed processing 1 files
2022/03/08 11:03:39Z goroutine 1 [running]:
runtime/debug.Stack(0x14a4580, 0xc0001cc970, 0xc0004cb968)
	/task_162931984430872/go/go/src/runtime/debug/stack.go:24 +0xa5
main.HandleCrash(0x153ed60, 0xc00043e340)
	/task_162931984430872/taskcluster/workers/generic-worker/main.go:319 +0x2d
main.RunWorker.func1(0xc0004cbe60)
	/task_162931984430872/taskcluster/workers/generic-worker/main.go:341 +0x5c
panic(0x153ed60, 0xc00043e340)
	/task_162931984430872/go/go/src/runtime/panic.go:971 +0x49a
main.RunWorker.func2(0xc0004cbb50)
	/task_162931984430872/taskcluster/workers/generic-worker/main.go:373 +0x68
main.RunWorker(0x45)
	/task_162931984430872/taskcluster/workers/generic-worker/main.go:504 +0x82b
main.main()
	/task_162931984430872/taskcluster/workers/generic-worker/main.go:158 +0x739
2022/03/08 11:03:39Z  *********** PANIC occurred! *********** 
2022/03/08 11:03:39Z exit status 1352
```

**Comment by petemoore** [comment]
Have you ever seen this since? Maybe an underlying Windows problem that can be masked if generic-worker retries on failure?
