### ISSUE TITLE
Docker worker S3 uploading intermittent failures

### ISSUE THREAD

**Issue by Eijebong** [taskcluster/taskcluster#5273]
It gets some `ECONNRESET` errors fairly frequently while trying to upload artifacts to S3.

Happens for both logs and job artifacts.

```
[taskcluster:error] Error uploading "public/spellers.tar.gz" artifact. read ECONNRESET
[taskcluster:error] Error: Error calling 'stopped' for artifactHandler : Error: Encountered error when uploading artifact(s)
    at Artifacts.stopped (/usr/local/bin/docker-worker/src/features/artifacts.js:227:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at Task.run (/usr/local/bin/docker-worker/src/task.js:943:7)
    at Task.start (/usr/local/bin/docker-worker/src/task.js:669:17)
    at TaskListener.runTask (/usr/local/bin/docker-worker/src/task_listener.js:474:9)
```

**Comment by petemoore** [comment]
Is the retry mechanism working, or after a single ECONNRESET does it give up?

**Comment by Eijebong** [comment]
When it's for the logs upload I get this in the worker logs though which seems to indicate that retying works
```
Mar 08 14:59:12 taskcluster-worker start-worker[394]: 2022/03/08 14:59:12 {"type":"Error uploading public/logs/live_backing.log","source":"uploadToS3","err":{"errno":-104,"code":"ECONNRESET","syscall":"read"},"taskId":"e2q4WQZbT0uCOjmtv1PiuA",
Mar 08 14:59:12 taskcluster-worker start-worker[394]: 2022/03/08 14:59:12 {"type":"Uploading public/logs/live_backing.log","source":"uploadToS3","taskId":"e2q4WQZbT0uCOjmtv1PiuA","runId":0,"artifactName":"public/logs/live_backing.log","putUrl"
Mar 08 14:59:12 taskcluster-worker start-worker[394]: 2022/03/08 14:59:12 {"type":"retrying artifact upload","source":"uploadToS3","taskId":"e2q4WQZbT0uCOjmtv1PiuA","runId":0,"artifactName":"public/logs/live_backing.log","putUrl":"https://divv
Mar 08 14:59:09 taskcluster-worker start-worker[394]: 2022/03/08 14:59:09 {"type":"Error uploading public/logs/live_backing.log","source":"uploadToS3","err":{"errno":-104,"code":"ECONNRESET","syscall":"read"},"taskId":"e2q4WQZbT0uCOjmtv1PiuA",
Mar 08 14:59:09 taskcluster-worker start-worker[394]: 2022/03/08 14:59:09 {"type":"Uploading public/logs/live_backing.log","source":"uploadToS3","taskId":"e2q4WQZbT0uCOjmtv1PiuA","runId":0,"artifactName":"public/logs/live_backing.log","putUrl"
Mar 08 14:59:09 taskcluster-worker start-worker[394]: 2022/03/08 14:59:09 {"type":"retrying artifact upload","source":"uploadToS3","taskId":"e2q4WQZbT0uCOjmtv1PiuA","runId":0,"artifactName":"public/logs/live_backing.log","putUrl":"https://divv
Mar 08 14:59:06 taskcluster-worker start-worker[394]: 2022/03/08 14:59:06 {"type":"Error uploading public/logs/live_backing.log","source":"uploadToS3","err":{"errno":-104,"code":"ECONNRESET","syscall":"read"},"taskId":"e2q4WQZbT0uCOjmtv1PiuA",
Mar 08 14:59:06 taskcluster-worker start-worker[394]: 2022/03/08 14:59:06 {"type":"Uploading public/logs/live_backing.log","source":"uploadToS3","taskId":"e2q4WQZbT0uCOjmtv1PiuA","runId":0,"artifactName":"public/logs/live_backing.log","putUrl"
Mar 08 14:59:06 taskcluster-worker start-worker[394]: 2022/03/08 14:59:06 {"type":"retrying artifact upload","source":"uploadToS3","taskId":"e2q4WQZbT0uCOjmtv1PiuA","runId":0,"artifactName":"public/logs/live_backing.log","putUrl":"https://divv
Mar 08 14:59:04 taskcluster-worker start-worker[394]: 2022/03/08 14:59:04 {"type":"Error uploading public/logs/live_backing.log","source":"uploadToS3","err":{"errno":-104,"code":"ECONNRESET","syscall":"read"},"taskId":"e2q4WQZbT0uCOjmtv1PiuA",
Mar 08 14:59:04 taskcluster-worker start-worker[394]: 2022/03/08 14:59:04 {"type":"Uploading public/logs/live_backing.log","source":"uploadToS3","taskId":"e2q4WQZbT0uCOjmtv1PiuA","runId":0,"artifactName":"public/logs/live_backing.log","putUrl"
Mar 08 14:59:04 taskcluster-worker start-worker[394]: 2022/03/08 14:59:04 {"type":"retrying artifact upload","source":"uploadToS3","taskId":"e2q4WQZbT0uCOjmtv1PiuA","runId":0,"artifactName":"public/logs/live_backing.log","putUrl":"https://divv
Mar 08 14:59:02 taskcluster-worker start-worker[394]: 2022/03/08 14:59:02 {"type":"Error uploading public/logs/live_backing.log","source":"uploadToS3","err":{"errno":-104,"code":"ECONNRESET","syscall":"read"},"taskId":"e2q4WQZbT0uCOjmtv1PiuA",
Mar 08 14:59:02 taskcluster-worker start-worker[394]: 2022/03/08 14:59:02 {"type":"Uploading public/logs/live_backing.log","source":"uploadToS3","taskId":"e2q4WQZbT0uCOjmtv1PiuA","runId":0,"artifactName":"public/logs/live_backing.log","putUrl"
```

**Comment by Eijebong** [comment]
Ok, for that particular artifact, while public logs don't show it was retried, on the worker log sides:

````
2022/03/08 12:57:09 {"type":"retrying artifact upload","source":"uploadToS3","taskId":"Vks14M1XTJSWfAUwYTYdgQ","runId":0,"artifactName":"public/spellers.tar.gz",
2022/03/08 12:57:02 {"type":"Error uploading public/spellers.tar.gz","source":"uploadToS3","err":{"errno":-104,"code":"ECONNRESET","syscall":"read"},"taskId":"Vk
2022/03/08 12:57:02 {"type":"Uploading public/spellers.tar.gz","source":"uploadToS3","taskId":"Vks14M1XTJSWfAUwYTYdgQ","runId":0,"artifactName":"public/spellers.
2022/03/08 12:57:02 {"type":"retrying artifact upload","source":"uploadToS3","taskId":"Vks14M1XTJSWfAUwYTYdgQ","runId":0,"artifactName":"public/spellers.tar.gz",
2022/03/08 12:56:58 {"type":"aliveness check","source":"top","provisionerId":"divvun","workerId":"linux-2","workerGroup":"ci","workerType":"linux","workerNodeTyp
2022/03/08 12:56:56 {"type":"Error uploading public/spellers.tar.gz","source":"uploadToS3","err":{"errno":-104,"code":"ECONNRESET","syscall":"read"},"taskId":"Vk
2022/03/08 12:56:56 {"type":"Uploading public/spellers.tar.gz","source":"uploadToS3","taskId":"Vks14M1XTJSWfAUwYTYdgQ","runId":0,"artifactName":"public/spellers.
2022/03/08 12:56:56 {"type":"retrying artifact upload","source":"uploadToS3","taskId":"Vks14M1XTJSWfAUwYTYdgQ","runId":0,"artifactName":"public/spellers.tar.gz",
2022/03/08 12:56:52 {"type":"Error uploading public/spellers.tar.gz","source":"uploadToS3","err":{"errno":-104,"code":"ECONNRESET","syscall":"read"},"taskId":"Vk
2022/03/08 12:56:51 {"type":"Uploading public/spellers.tar.gz","source":"uploadToS3","taskId":"Vks14M1XTJSWfAUwYTYdgQ","runId":0,"artifactName":"public/spellers.
2022/03/08 12:56:51 {"type":"retrying artifact upload","source":"uploadToS3","taskId":"Vks14M1XTJSWfAUwYTYdgQ","runId":0,"artifactName":"public/spellers.tar.gz",
2022/03/08 12:56:48 {"type":"Error uploading public/spellers.tar.gz","source":"uploadToS3","err":{"errno":-104,"code":"ECONNRESET","syscall":"read"},"taskId":"Vk
2022/03/08 12:56:48 {"type":"Uploading public/spellers.tar.gz","source":"uploadToS3","taskId":"Vks14M1XTJSWfAUwYTYdgQ","runId":0,"artifactName":"public/spellers.
2022/03/08 12:56:48 {"type":"retrying artifact upload","source":"uploadToS3","taskId":"Vks14M1XTJSWfAUwYTYdgQ","runId":0,"artifactName":"public/spellers.tar.gz",
2022/03/08 12:56:45 {"type":"Error uploading public/spellers.tar.gz","source":"uploadToS3","err":{"errno":-104,"code":"ECONNRESET","syscall":"read"},"taskId":"Vk
2022/03/08 12:56:44 {"type":"Uploading public/spellers.tar.gz","source":"uploadToS3","taskId":"Vks14M1XTJSWfAUwYTYdgQ","runId":0,"artifactName":"public/spellers.
2022/03/08 12:56:44 {"type":"retrying artifact upload","source":"uploadToS3","taskId":"Vks14M1XTJSWfAUwYTYdgQ","runId":0,"artifactName":"public/spellers.tar.gz",
2022/03/08 12:56:42 {"type":"Error uploading public/spellers.tar.gz","source":"uploadToS3","err":{"errno":-104,"code":"ECONNRESET","syscall":"read"},"taskId":"Vk
2022/03/08 12:56:42 {"type":"Uploading public/spellers.tar.gz","source":"uploadToS3","taskId":"Vks14M1XTJSWfAUwYTYdgQ","runId":0,"artifactName":"public/spellers.
2022/03/08 12:56:42 {"type":"retrying artifact upload","source":"uploadToS3","taskId":"Vks14M1XTJSWfAUwYTYdgQ","runId":0,"artifactName":"public/spellers.tar.gz",
2022/03/08 12:56:41 {"type":"Error uploading public/spellers.tar.gz","source":"uploadToS3","err":{"errno":-104,"code":"ECONNRESET","syscall":"read"},"taskId":"Vk
2022/03/08 12:56:41 {"type":"Uploading public/spellers.tar.gz","source":"uploadToS3","taskId":"Vks14M1XTJSWfAUwYTYdgQ","runId":0,"artifactName":"public/spellers.
```

**Comment by djmitche** [comment]
How intermittent is this?  Is it possible to get a tcpdump of the issue?  ECONNRESET is pretty closely tied to `RST` frames from the remote end, so it'd be interesting to figure out why S3 is serving up `RST`'s..

**Comment by Eijebong** [comment]
Out of the 139 decision tasks I had today it happened ~10 times? So pretty frequent I would say.

**Comment by Eijebong** [comment]
```
2022/03/06 12:13:04Z Could not claim work. 
CALL SUMMARY
============
Method: POST
Service: divvun-tc.thetc.se:
Response Body:
{
  "code": "AuthenticationFailed",
  "message": "ext.certificate.expiry < now\n\n---\n\n* method:     claimWork\n* errorCode:  AuthenticationFailed\n* statusCode: 401\n* time:       2022-03-06T12:13:04.935Z",
  "requestInfo": {
    "method": "claimWork",
    "params": {
      "0": "divvun/windows",
      "taskQueueId": "divvun/windows"
    },
    "payload": {
      "tasks": 1,
      "workerGroup": "ci",
      "workerId": "windows-2"
    },
    "time": "2022-03-06T12:13:04.935Z"
  }
}
Attempts: 1
(Permanent) HTTP response code 401
HTTP/2.0 401 Unauthorized
```

Got that a lot from generic-worker but nothing between 

```
2022/02/28 12:48:17 Writing files
2022/02/28 12:48:17 Starting worker
2022/02/28 12:48:17 Worker credentials expire in 95h59m59s
```

and 

```
2022/03/08 12:03:58 Loading worker-runner configuration from c:\worker-runner\runner.yml
2022/03/08 12:03:58 Configuring with provider static
2022/03/08 12:03:58 Identified as worker ci/windows-2
2022/03/08 12:03:58 Getting secrets from secrets service
2022/03/08 12:03:58 WARNING: No worker secrets for worker pool divvun/windows.
2022/03/08 12:03:58 Configuring for worker implementation generic-worker
```

**Comment by Eijebong** [comment]
@djmitche There we go, this is a capture when it fails to upload a log file (pretty short file). 

[rst_upload.pcap.zip](https://github.com/taskcluster/taskcluster/files/8223199/rst_upload.pcap.zip)

**Comment by djmitche** [comment]
```
225.110.101.5.in-addr.arpa domain name pointer ams3.digitaloceanspaces.com.
```
I didn't realize this was the DO emulation.  Is it possible there's some API limit you're hitting? Maximum object size, or something like that?

Let's look at the conversation:
```
# -> SYN
05:28:17.740296 IP (tos 0x0, ttl 64, id 63188, offset 0, flags [DF], proto TCP (6), length 60)
    192.168.122.204.34094 > 5.101.110.225.443: Flags [S], cksum 0x83b2 (correct), seq 1013334544, win 64240, options [mss 1460,sackOK,TS val 2745069731 ecr 0,nop,wscale 7], length 0
# <- SYN + ACK
05:28:17.771436 IP (tos 0x0, ttl 54, id 0, offset 0, flags [DF], proto TCP (6), length 60)
    5.101.110.225.443 > 192.168.122.204.34094: Flags [S.], cksum 0xbef5 (correct), seq 4212839949, ack 1013334545, win 62636, options [mss 8960,sackOK,TS val 2913939147 ecr 2745069731,nop,wscale 7], length 0
# -> ACK -- connection established normally
05:28:17.771503 IP (tos 0x0, ttl 64, id 63189, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.122.204.34094 > 5.101.110.225.443: Flags [.], cksum 0xfda4 (correct), seq 1, ack 1, win 502, options [nop,nop,TS val 2745069763 ecr 2913939147], length 0
# -> PSH with 382 bytes of data -- ClientHello (382 bytes) (the servname appears in this frame)
05:28:17.771630 IP (tos 0x0, ttl 64, id 63190, offset 0, flags [DF], proto TCP (6), length 434)
    192.168.122.204.34094 > 5.101.110.225.443: Flags [P.], cksum 0x08d3 (correct), seq 1:383, ack 1, win 502, options [nop,nop,TS val 2745069763 ecr 2913939147], length 382
# <- ACK
05:28:17.802687 IP (tos 0x0, ttl 54, id 40002, offset 0, flags [DF], proto TCP (6), length 52)
    5.101.110.225.443 > 192.168.122.204.34094: Flags [.], cksum 0xfc16 (correct), seq 1, ack 383, win 487, options [nop,nop,TS val 2913939178 ecr 2745069763], length 0
# <- ServerHello? (1448 bytes, maybe just a fragment?)
05:28:17.804776 IP (tos 0x0, ttl 54, id 40003, offset 0, flags [DF], proto TCP (6), length 1500)
    5.101.110.225.443 > 192.168.122.204.34094: Flags [.], cksum 0xb2a3 (correct), seq 1:1449, ack 383, win 487, options [nop,nop,TS val 2913939181 ecr 2745069763], length 1448
# -> ACK
05:28:17.804821 IP (tos 0x0, ttl 64, id 63191, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.122.204.34094 > 5.101.110.225.443: Flags [.], cksum 0xf63c (correct), seq 383, ack 1449, win 501, options [nop,nop,TS val 2745069796 ecr 2913939181], length 0
# <- more data (1448 bytes, so probably not ServerHello)
05:28:17.804943 IP (tos 0x0, ttl 54, id 40004, offset 0, flags [DF], proto TCP (6), length 1500)
    5.101.110.225.443 > 192.168.122.204.34094: Flags [P.], cksum 0xfed5 (correct), seq 1449:2897, ack 383, win 487, options [nop,nop,TS val 2913939181 ecr 2745069763], length 1448
# <- more data (596 bytes)
05:28:17.804946 IP (tos 0x0, ttl 54, id 40005, offset 0, flags [DF], proto TCP (6), length 648)
    5.101.110.225.443 > 192.168.122.204.34094: Flags [P.], cksum 0x87e3 (correct), seq 2897:3493, ack 383, win 487, options [nop,nop,TS val 2913939181 ecr 2745069763], length 596
# -> ACK some of that
05:28:17.804971 IP (tos 0x0, ttl 64, id 63192, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.122.204.34094 > 5.101.110.225.443: Flags [.], cksum 0xf094 (correct), seq 383, ack 2897, win 501, options [nop,nop,TS val 2745069796 ecr 2913939181], length 0
# -> ACK all of that
05:28:17.805114 IP (tos 0x0, ttl 64, id 63193, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.122.204.34094 > 5.101.110.225.443: Flags [.], cksum 0xee40 (correct), seq 383, ack 3493, win 501, options [nop,nop,TS val 2745069796 ecr 2913939181], length 0
# -> PSH some data (a lot of data -- 2896 byte packet, larger than the usual 1448 MTU)
05:28:17.805819 IP (tos 0x0, ttl 64, id 63194, offset 0, flags [DF], proto TCP (6), length 2948)
    192.168.122.204.34094 > 5.101.110.225.443: Flags [P.], cksum 0x3a56 (correct), seq 383:3279, ack 3493, win 501, options [nop,nop,TS val 2745069797 ecr 2913939181], length 2896
# -> ..keep pushing up to 11966 bytes
05:28:17.805866 IP (tos 0x0, ttl 64, id 63196, offset 0, flags [DF], proto TCP (6), length 2948)
    192.168.122.204.34094 > 5.101.110.225.443: Flags [P.], cksum 0xe774 (correct), seq 3279:6175, ack 3493, win 501, options [nop,nop,TS val 2745069797 ecr 2913939181], length 2896
05:28:17.805910 IP (tos 0x0, ttl 64, id 63198, offset 0, flags [DF], proto TCP (6), length 2948)
    192.168.122.204.34094 > 5.101.110.225.443: Flags [P.], cksum 0xf389 (correct), seq 6175:9071, ack 3493, win 501, options [nop,nop,TS val 2745069797 ecr 2913939181], length 2896
05:28:17.806011 IP (tos 0x0, ttl 64, id 63200, offset 0, flags [DF], proto TCP (6), length 2948)
    192.168.122.204.34094 > 5.101.110.225.443: Flags [P.], cksum 0xe985 (correct), seq 9071:11967, ack 3493, win 501, options [nop,nop,TS val 2745069797 ecr 2913939181], length 2896
05:28:17.806031 IP (tos 0x0, ttl 64, id 63202, offset 0, flags [DF], proto TCP (6), length 2948)
    192.168.122.204.34094 > 5.101.110.225.443: Flags [P.], cksum 0x2340 (correct), seq 11967:14863, ack 3493, win 501, options [nop,nop,TS val 2745069797 ecr 2913939181], length 2896
# <- RST's for each PSH -- the server didn't like those pushes
05:28:17.837155 IP (tos 0x0, ttl 54, id 0, offset 0, flags [DF], proto TCP (6), length 40)
    5.101.110.225.443 > 192.168.122.204.34094: Flags [R], cksum 0x9a6e (correct), seq 4212843442, win 0, length 0
05:28:17.837242 IP (tos 0x0, ttl 54, id 0, offset 0, flags [DF], proto TCP (6), length 40)
    5.101.110.225.443 > 192.168.122.204.34094: Flags [R], cksum 0x9a6e (correct), seq 4212843442, win 0, length 0
05:28:17.837335 IP (tos 0x0, ttl 54, id 0, offset 0, flags [DF], proto TCP (6), length 40)
    5.101.110.225.443 > 192.168.122.204.34094: Flags [R], cksum 0x9a6e (correct), seq 4212843442, win 0, length 0
05:28:17.837339 IP (tos 0x0, ttl 54, id 0, offset 0, flags [DF], proto TCP (6), length 40)
    5.101.110.225.443 > 192.168.122.204.34094: Flags [R], cksum 0x9a6e (correct), seq 4212843442, win 0, length 0
05:28:17.837456 IP (tos 0x0, ttl 54, id 0, offset 0, flags [DF], proto TCP (6), length 40)
    5.101.110.225.443 > 192.168.122.204.34094: Flags [R], cksum 0x9a6e (correct), seq 4212843442, win 0, length 0
```

I can't distinguish TLS setup from HTTP requests in this context, but it looks like the server decides somewhere early in the connection that it's not happy with what hte client has sent, sends back a few KB, and then closes the connection (triggering the RSTs).

I guess the next step is to figure out what the error is.

I suspect the JS http client is getting both a connection reset and an error message, and it's a race to see which one gets reported -- a race the ECONNRESET is winning.  I saw a similar thing with the Go http client recently.  I think this "NO, GO AWAY, RST RST RST" behavior from servers is relatively new and maybe clients haven't quite sorted it out yet.

I suspect the next step would be to try to reproduce this outside of the worker, using digitalocean, and then either try to convince the JS http client to show the right error, or get the TLS session keys so that we can decrypt the capture and see the error.

**Comment by Eijebong** [comment]
Welp.

https://github.com/taskcluster/taskcluster/blob/841aab318e282aaebddefa5adcce60da86d18ecb/workers/docker-worker/src/upload_to_s3.js#L53

This is wrong. `tmp.writeFile` is not an async function, that await does nothing. And in today's javascript thing I didn't want to know:
```
js> (async () => { await undefined })()
({})
```

https://github.com/vesln/temporary/blob/4e79961ff07a0bdf984dca37392c86ae31a3f75f/lib/file.js#L57

In my local test, the file was 0 sized on every call but I removed a call to the `queue` service between that and the actual upload. 
This doesn't seem to be used but doesn't fill me with confidence on the rest of the code :)

**Comment by Eijebong** [comment]
https://github.com/taskcluster/taskcluster/blob/841aab318e282aaebddefa5adcce60da86d18ecb/workers/docker-worker/src/upload_to_s3.js#L68

Pretty sure this is also very wrong, it'll always be 0 unless the source is a string. So we're just sending `content-length: 0` on every request AFAICT.

**Comment by Eijebong** [comment]
I feel like I have to be missing a magic write into `tmp` because that would mean that after a retry it would be reading from an empty file

https://github.com/taskcluster/taskcluster/blob/841aab318e282aaebddefa5adcce60da86d18ecb/workers/docker-worker/src/upload_to_s3.js#L133

**Comment by Eijebong** [comment]
Turns out nodejs or linux or both don't like `e1000e` netcards on my VMs. Changing it to virtio seems to have magically solved the issue...

Here's the script I used to reproduce the issue. Reproduced very easily on e1000e, couldn't reproduce on virtio. I'll close the issue and open one about the `tmp.writeFile` because that's still wrong in docker-worker.

```js
const zlib = require('zlib');
const crypto = require('crypto');
const https = require('https');
const url = require('url');
const fs = require('mz/fs');
const temporary = require('temporary');
const promiseRetry = require('promise-retry');
const _ = require('lodash');
const pipe = require('promisepipe');
const { Transform } = require('stream');
var AWS = require('aws-sdk');
var s3 = new AWS.S3({
  signatureVersion: 'v4',
  endpoint: "https://ams3.digitaloceanspaces.com/",
});



// Upload an S3 artifact to the queue for the given taskId/runId.  Source can be
// a string or a stream.
async function uploadToS3 (
  source,
  artifactName,
  httpsHeaders,
  putUrl,
  httpOptions,
  compress)
{
  let tmp = new temporary.File();
  console.log(`created temporary file $${tmp.path} for ${artifactName}`);

  let logDetails = { artifactName };
  let digest;
  let size;

  try {
    // Create a transform stream so that we can hash the original file as we
    // read it from the source stream
    let hash = crypto.createHash('sha256');
    let hashingTransform = new Transform({
      transform(chunk, encoding, callback) {
        hash.update(chunk);
        this.push(chunk);
        callback();
      },
    });

    // write the source out to a temporary file so that it can be
    // re-read into the request repeatedly
    if (typeof source === 'string') {
      console.log()
      tmp.writeFileSync(source);
      hash.update(source);
    } else {
      let stream = fs.createWriteStream(tmp.path);
      if (compress) {
        let gzip = zlib.createGzip();
        console.log(`compressing to ${artifactName} to ${tmp.path}`);
        await pipe(source, hashingTransform, gzip, stream);
        console.log(`compressed ${gzip.bytesWritten} bytes`);
      } else {
        await pipe(source, hashingTransform, stream);
      }
    }
    let stat = await fs.stat(tmp.path);
    size = stat.size;
    httpsHeaders['content-length'] = size;

    console.log(`wrote ${size} bytes of source file to ${tmp.path} for ${artifactName}`);

    if (!putUrl) {
        console.log("No PUT URL provided, please do, we don't have a queue here")
    }

    logDetails.putUrl = putUrl;

    let parsedUrl = url.parse(putUrl);
    let options = _.defaults({
      hostname: parsedUrl.hostname,
      path: parsedUrl.path,
      method: 'PUT',
      headers: httpsHeaders,
      port: parsedUrl.port,
    }, httpOptions);

    // promiseRetry defaults to 10 attempts before failing
    await promiseRetry((retry, number) => {
      if (number > 1) { // if it's not the first attempt
        console.log('retrying artifact upload', _.defaults({}, logDetails, {
          attemptNumber: number,
        }));
      }

      return new Promise((accept, reject) => {
        let req = https.request(options);

        req.on('response', (response) => {
          // Flush the data from the reponse so it's not held in memory
          response.resume();

          if (response.statusCode !== 200) {
            reject(new Error(
              `Could not upload artifact. Status Code: ${response.statusCode}`,
            ));
          } else {
            digest = hash.digest('hex');
            logDetails.hash = digest;
            accept();
          }
        });

        req.on('error', err => {
          console.log(`Error uploading ${artifactName}`, _.defaults({ err }, logDetails));
          reject(err);
        });

        req.setTimeout(5 * 60 * 1000, reject);

        const readStream = fs.createReadStream(tmp.path);
        readStream.on('error', err => {
          console.log(`Error reading temp file while uploading ${artifactName}`, _.defaults({ err }, logDetails));
          reject(err);
        });

        console.log(`Uploading ${artifactName}`, logDetails);
        readStream.pipe(req);
      }).catch(retry);
    // The formula to calculate the next attempt timeout is:
    // Math.min(random * minTimeout * Math.pow(factor, attempt), maxTimeout)
    // We have:
    //  maxTimeout = 30 seconds
    //  minTimeout = 1 second
    //  10 attempts
    //  random factor = 1..2
    // The first parameter of the min function can have a maximum value of
    //  2 * 1000 * Math.pow(factor, 10)
    // This value is bounded by maxTimeout. To avoid early saturation of the
    // calculated value, we must choose a value for factor that in the worst
    // case scenario should not be greater than maxTimeout, i.e.:
    //  2 * 1000 * Math.pow(factor, 10) <= 30000
    // Solving the equation for factor gives factor=1.311
    }, { maxTimeout: 30000, factor: 1.311, randomize: true });
  } finally {
    tmp.unlinkSync();
  }

  return { digest, size };
};


(async () => {
    try {
        let tries = 0
        while (tries < 500) {
            const source = fs.createReadStream("./yarn.lock");
            const artifactName = "test"
            const httpsHeaders = {}
            const bucketName = "divvun"
            var key = "test"
            const signedUrlExpireSeconds = 60 * 5;
            const putUrl = s3.getSignedUrl('putObject', {
                Bucket: bucketName,
                Key: key,
                Expires: signedUrlExpireSeconds,
            });

            console.log('presigned url: ', putUrl);

            const text = await uploadToS3(source, artifactName, httpsHeaders, putUrl);
            console.log(text);
        }
    } catch (e) {
        console.log(e)
        // Deal with the fact the chain failed
    }
    // `text` is not available here
})();
```

**Comment by lotas** [comment]
Wow! Thanks for debugging all of this and finding the issue :+1:

**Comment by djmitche** [comment]
That is _truly_ bizarre.  I wonder if some kind of TCP offload has a bug in that particular driver?  That would probably also mean we wouldn't see it in the tcpdump output.
