### ISSUE TITLE
"Error: Invalid token" messages from auth service

### ISSUE THREAD

**Issue by lotas** [taskcluster/taskcluster#5421]
```
Error: Invalid token
    at Client.<anonymous> (/app/node_modules/sentry-api/lib/client.js:138:19)
    at Request.self.callback (/app/node_modules/request/request.js:185:22)
    at Request.emit (node:events:527:28)
    at Request.emit (node:domain:475:12)
    at Request.<anonymous> (/app/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:527:28)
    at Request.emit (node:domain:475:12)
    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:641:28)
    at IncomingMessage.emit (node:events:539:35)
    at IncomingMessage.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

```
{
  "insertId": "d9l4juo6sfrwbsep",
  "jsonPayload": {
    "message": "Error: Invalid token\n    at Client.<anonymous> (/app/node_modules/sentry-api/lib/client.js:138:19)\n    at Request.self.callback (/app/node_modules/request/request.js:185:22)\n    at Request.emit (node:events:527:28)\n    at Request.emit (node:domain:475:12)\n    at Request.<anonymous> (/app/node_modules/request/request.js:1154:10)\n    at Request.emit (node:events:527:28)\n    at Request.emit (node:domain:475:12)\n    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1076:12)\n    at Object.onceWrapper (node:events:641:28)\n    at IncomingMessage.emit (node:events:539:35)\n    at IncomingMessage.emit (node:domain:475:12)\n    at endReadableNT (node:internal/streams/readable:1345:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n",
    "Severity": 3,
    "requestId": "24fa0409-4d25-4446-8771-ae7b731cd933",
    "traceId": "db38ab6bd05277b07c4dcd5e6ab52cd3",
    "Pid": 1,
    "Timestamp": 1651676940489000000,
    "Logger": "taskcluster.auth.api",
    "Fields": {
      "incidentId": "fd4600bc-79c4-4e7c-bead-9aa41ddca2fa",
      "method": "sentryDSN",
      "v": 1,
      "message": "Invalid token",
      "name": "Error",
      "stack": "Error: Invalid token\n    at Client.<anonymous> (/app/node_modules/sentry-api/lib/client.js:138:19)\n    at Request.self.callback (/app/node_modules/request/request.js:185:22)\n    at Request.emit (node:events:527:28)\n    at Request.emit (node:domain:475:12)\n    at Request.<anonymous> (/app/node_modules/request/request.js:1154:10)\n    at Request.emit (node:events:527:28)\n    at Request.emit (node:domain:475:12)\n    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1076:12)\n    at Object.onceWrapper (node:events:641:28)\n    at IncomingMessage.emit (node:events:539:35)\n    at IncomingMessage.emit (node:domain:475:12)\n    at endReadableNT (node:internal/streams/readable:1345:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)"
    },
    "EnvVersion": "2.0",
    "Hostname": "taskcluster-auth-web-7f955bb85d-bv8hl",
    "Type": "monitor.error",
    "serviceContext": {
      "version": "44.13.4",
      "service": "auth"
    }
  },
  "resource": {
    "type": "k8s_container",
    "labels": {
      "location": "us-west1",
      "project_id": "moz-fx-taskcluster-prod-4b87",
      "container_name": "taskcluster-auth-web",
      "pod_name": "taskcluster-auth-web-7f955bb85d-bv8hl",
      "cluster_name": "taskcluster-firefoxcitc-v1",
      "namespace_name": "firefoxcitc-taskcluster"
    }
  },
  "timestamp": "2022-05-04T15:09:00.489697541Z",
  "severity": "ERROR",
  "labels": {
    "k8s-pod/app_kubernetes_io/name": "taskcluster-auth",
    "k8s-pod/app_kubernetes_io/instance": "firefoxcitc-taskcluster-taskcluster-1",
    "k8s-pod/pod-template-hash": "7f955bb85d",
    "k8s-pod/app_kubernetes_io/component": "taskcluster-auth-web",
    "k8s-pod/app_kubernetes_io/part-of": "taskcluster",
    "compute.googleapis.com/resource_name": "gke-taskcluster-firef-default-pool-v1-9c59e3de-k385"
  },
  "logName": "projects/moz-fx-taskcluster-prod-4b87/logs/stdout",
  "receiveTimestamp": "2022-05-04T15:09:19.150862244Z"
}
```

**Comment by djmitche** [comment]
It looks like those are coming from the [`auth.sentryDSN`](https://docs.taskcluster.net/docs/reference/platform/auth/api#sentryDSN) endpoint.  IIRC sentry was an error-reporting service that we abandoned some years ago, but I think generic-worker still contains code using it.  I think the token is invalid because it's not set (or the account is closed anyway).  It would probably be good to either remove the endpoint from the auth service altogether, or at least have the method handle this circumstance without throwing an exception (maybe a 404?)

**Comment by djmitche** [comment]
..oh, and remove generic-worker's use of the API method :)

**Comment by lotas** [comment]
The funny thing that this is error is coming from Sentry :) So I think the deployment configuration is correct and provides a valid sentry link, because Taskcluster is reporting quite a few errors. Or maybe those are different configurations.

@djmitche I thought sentry was important for workers, so they still use this endpoint to get sentry credentials and report problems. I'll check

**Comment by djmitche** [comment]
Ah, sorry, I must have been remembering some other ops deprecation!
