### ISSUE TITLE
Generic-worker crash on macos when trying to spawn `taskcluster-proxy` but unable to do so

### ISSUE THREAD

**Issue by Eijebong** [taskcluster/taskcluster#5785]
Not entirely sure why, I can see that the worker leaves a lot of `taskcluster-proxy` zombies behind, might be related.

```
[taskcluster:error] Could not start taskcluster proxy: fork/exec bin/taskcluster-proxy: resource temporarily unavailable
[taskcluster:error] goroutine 1 [running]:
[taskcluster:error] runtime/debug.Stack(0xc000bed418, 0x1534ec0, 0x1991890)
[taskcluster:error] 	/task_162931984430872/go/go/src/runtime/debug/stack.go:24 +0x9f
[taskcluster:error] main.(*TaskRun).Run.func2(0xc0000a8780, 0xc000116300, 0xc0000a8788)
[taskcluster:error] 	/task_162931984430872/taskcluster/workers/generic-worker/main.go:895 +0x41c
[taskcluster:error] panic(0x1534ec0, 0x1991890)
[taskcluster:error] 	/task_162931984430872/go/go/src/runtime/panic.go:971 +0x499
[taskcluster:error] github.com/taskcluster/taskcluster/v44/workers/generic-worker/tcproxy.(*TaskclusterProxy).Terminate(0x0, 0x0, 0x0)
[taskcluster:error] 	/task_162931984430872/taskcluster/workers/generic-worker/tcproxy/tcproxy.go:61 +0x47
[taskcluster:error] main.(*TaskclusterProxyTask).Stop(0xc0002e5710, 0xc0002e4e10)
[taskcluster:error] 	/task_162931984430872/taskcluster/workers/generic-worker/taskcluster_proxy.go:119 +0x56
[taskcluster:error] main.(*TaskRun).Run.func3(0xc0000a8780, 0x16cc3e8, 0xc0002e5710, 0x16cd518, 0x19d0208)
[taskcluster:error] 	/task_162931984430872/taskcluster/workers/generic-worker/main.go:977 +0xc6
[taskcluster:error] main.(*TaskRun).Run(0xc000116300, 0x9)
[taskcluster:error] 	/task_162931984430872/taskcluster/workers/generic-worker/main.go:981 +0xae0
[taskcluster:error] main.RunWorker(0x0)
[taskcluster:error] 	/task_162931984430872/taskcluster/workers/generic-worker/main.go:426 +0x727
[taskcluster:error] main.main()
[taskcluster:error] 	/task_162931984430872/taskcluster/workers/generic-worker/main.go:158 +0x7aa
[taskcluster:error] 
[taskcluster:error] "invalid memory address or nil pointer dereference"
[taskcluster:error] runtime error: invalid memory address or nil pointer dereference
```

**Comment by petemoore** [comment]
Thanks @Eijebong! Which version of generic-worker is this?

On main, the line that panics seems to be this one, but that confuses me, as grabbing a mutex shouldn't cause a fork/exec failure!

https://github.com/taskcluster/taskcluster/blob/main/workers/generic-worker/tcproxy/tcproxy.go#L61

The generic-worker logs should report when they terminate taskcluster-proxy, and also when they start it. Do you see anything suspicious there?

**Comment by Eijebong** [comment]
Oh right, I always forget. This is `44.2.2`.

**Comment by Eijebong** [comment]
Also doesn't `[taskcluster:error] github.com/taskcluster/taskcluster/v44/workers/generic-worker/tcproxy.(*TaskclusterProxy).Terminate(0x0, 0x0, 0x0)` mean that `l` here is `0x0`? That would explain why.

My guess is that the worker calls terminate if the proxy fails to spawn. So let's dig up...

If we go back from the stacktrace with the hypothesis that `l` is indeed `0x0` it would mean that it was never set to anything. The only way this happens is if we take the error branch here.

https://github.com/taskcluster/taskcluster/blob/153118062b9af22fa50b17e7d1ad14e340ac3960/workers/generic-worker/taskcluster_proxy.go#L78-L81

This happens if the proxy couldn't be created which is promising given the `[taskcluster:error] Could not start taskcluster proxy: fork/exec bin/taskcluster-proxy: resource temporarily unavailable` message.

Now after a bit more digging and a few indirections, we arrive here, https://github.com/taskcluster/taskcluster/blob/153118062b9af22fa50b17e7d1ad14e340ac3960/workers/generic-worker/main.go#L933 where it creates a `TaskclusterProxyFeature`.

It then calls `Start` and defers `Stop` here: https://github.com/taskcluster/taskcluster/blob/153118062b9af22fa50b17e7d1ad14e340ac3960/workers/generic-worker/main.go#L971-L978

As we can see, it calls `Stop` whether `Start` succeeds or not.

`Stop` calls `l.taskclusterProxy.Terminate()` here https://github.com/taskcluster/taskcluster/blob/153118062b9af22fa50b17e7d1ad14e340ac3960/workers/generic-worker/taskcluster_proxy.go#L119
but `l.taskclusterProxy` was never set. :boom:

**Comment by Eijebong** [comment]
This was fixed by 4d3c356b6bcd7ad87136eb9303add25db48c002e
