### ISSUE TITLE
Github service encounters rate limiting

### ISSUE THREAD

**Issue by lotas** [taskcluster/taskcluster#5914]
Few days ago we had about 20-25 dependabot PR that were constantly rebased due to misconfiguration, which triggered many new jobs. 
Those jobs were calling github API in turn, which lead to hitting API rate limits.
Some updates were lost because of this, and statuses could not be updated for those check runs

Typical entries in logs:

```
PATCH /repos/taskcluster/taskcluster/check-runs/10185435319 - 403 in 164ms"

HttpError: API rate limit exceeded for installation ID 2255173.
    at /app/node_modules/@octokit/request/dist-node/index.js:86:21
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Job.doExecute (/app/node_modules/bottleneck/light.js:405:18)
```

This is obviously bad for the PRs that would never receive those status updates.

<img width="1203" alt="image" src="https://user-images.githubusercontent.com/83861/208918825-d43abef6-28e7-4103-a57d-530f6ba25db7.png">

**Comment by lotas** [comment]
maybe we want to have a separate queue for retrying, or a cronjob that would check few few times a day what updates failed and would try to update them again

**Comment by petemoore** [comment]
> First approach seems to be the easiest but also involves implementation of such messages that can be re-sent to queue and retried in future. In case of what happened with dependabot, this might create a forever rolling avalanche of github calls, API rate limits and retries.

Would exponential backoff help here?

**Comment by lotas** [comment]
> Would exponential backoff help here?

if those events happened at the same time (as it did on that occasion) then it would probably mean they would be scheduled for about the same intervals. Yes it might help as they will "spread-out" a bit, but it could also happen that they will no longer be relevant once they hit handler again.

RabbitMQ does not allow scheduling afaik, so we would have to implement something in code. Which is also error prone if pod will be terminated, we'd loose this information.

Github client is already doing retries on its own, but I guess with few hundreds simultaneous calls it will not be able to solve the api rate limiting issues.

Would be happy to discuss how we can solve this.
