### ISSUE TITLE
Worker manager shows incorrect number of running instances 

### ISSUE THREAD

**Issue by lotas** [taskcluster/taskcluster#6117]
There was an incident where generic-worker process was paniced and exited, while keeping instance running for several days.

Worker pool showed number of instances including this one, but when going into "list workers" view, it was not displayed there.

Further investigation showed that worker record existed in `workers` table but not in `queue_workers` which probably caused this not showing up issue.

> I've got 2 clogged worker pools.. https://community-tc.services.mozilla.com/worker-manager/proj-fuzzing%2Fwindows-pool55 and https://community-tc.services.mozilla.com/worker-manager/proj-fuzzing%2Fwindows-pool85 both have idle workers that are "running" but not claiming tasks.
> pool55 also says 2 running but I can only see 1

> `i-0d08846ed25267639` appears in logs within few hours after it was created, on 18th..
> then last message from websocktunnel `session removed` and that's it

Worker died because of OOM:
```
2023/03/18 16:20:14Z Error: Post "https://community-tc.services.mozilla.com/api/queue/v1/task/CUFljGCBS6mMV7Z8YxtRtA/runs/0/reclaim": dial tcp 34.102.144.36:443: bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full.

2023/03/18 16:21:04Z Received task status change: Reclaimed
panic: Could not PUT to http://localhost:80/credentials: Put "http://localhost:80/credentials": dial tcp [::1]:80: bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full.

goroutine 55 [running]:
main.(*TaskclusterProxyTask).Start.func1({0x93f172, 0x9})
	/task_167821116098671/taskcluster/workers/generic-worker/taskcluster_proxy.go:103 +0x56b
main.(*TaskStatusManager).updateStatus(0xc0006fe7e0, {0x93f172, 0x9}, 0xc000fb5e90, {0xc0003be1a0?, 0x2, 0x2})
	/task_167821116098671/taskcluster/workers/generic-worker/taskstatus.go:304 +0x60d
main.(*TaskStatusManager).reclaim(0xc0006fe7e0)
	/task_167821116098671/taskcluster/workers/generic-worker/taskstatus.go:157 +0x8a
main.NewTaskStatusManager.func1()
	/task_167821116098671/taskcluster/workers/generic-worker/taskstatus.go:367 +0x44f
created by main.NewTaskStatusManager
	/task_167821116098671/taskcluster/workers/generic-worker/taskstatus.go:340 +0x1d8

```

**Comment by lotas** [comment]
Same happens with workers who were expired recently in queue - https://community-tc.services.mozilla.com/provisioners/proj-taskcluster/worker-types/gw-ubuntu-22-04/workers/us-east1/177234637506064323 

`workers` table holds this record and has expiration `+5d` while `queue_workers` has a much lower expiration `~+1d` so api thinks this record is expired and doesn't return any records.

This also happens when `queue` "looses" info about worker as it has lower expiration time, so it is no longer possible to see such worker in the UI anymore. 

I think we should always show something as long as record exists and is worker itself is not expired. This might help to debug issues with workers that die and stop talking to queue

**Comment by lotas** [comment]
we have added separate queue and w-m views, which show all workers w-m created, and might not show some in queue view since they stopped talking to it
