### ISSUE TITLE
Object Service returning HTTP 500 responses

### ISSUE THREAD

**Issue by petemoore** [taskcluster/taskcluster#6308]
**Describe the bug**
In #6274 I got the generic-worker tests running against real services again, instead of just mocks.

The test TestObjectArtifact causes the (real) Object Service to return HTTP 500 errors.

**To Reproduce**

```
$ GW_TESTS_USE_EXTERNAL_TASKCLUSTER=true
$ TASKCLUSTER_ROOT_URL=....
$ TASKCLUSTER_CLIENT_ID=....
$ TASKCLUSTER_ACCESS_TOKEN=.....
$ TASKCLUSTER_CERTIFICATE=.....  # if using a temporary client
$ cd workers/generic-worker
$ vim artifacts_test.go   # remove the t.Skip(...) from test TestObjectArtifact
$ go test -v -tags simple -run TestObjectArtifact
```

**Expected behavior**

Test passes

Instead, we get errors like:

```json
{
  "code": "InternalServerError",
  "message": "Internal Server Error, incidentId 52e06a38-7230-43c2-9e61-bb3498fe3358.\n\n---\n\n* method:     createArtifact\n* errorCode:  InternalServerError\n* statusCode: 500\n* time:       2023-06-02T12:50:43.663Z",
  "requestInfo": {
    "method": "createArtifact",
    "params": {
      "0": "object-test.txt",
      "taskId": "Run3nRu7QFy4-JrOtI_xlw",
      "runId": "0",
      "name": "object-test.txt"
    },
    "payload": {
      "contentType": "application/octet-stream",
      "expires": "2023-06-16T12:49:27.000Z",
      "storageType": "object"
    },
    "time": "2023-06-02T12:50:43.663Z"
  }
}
```

**Additional context**

Looking at the above incident ID in gcloud, I see:

```json
[
  {
    "insertId": "0d4z4i5od8fetw2l",
    "jsonPayload": {
      "EnvVersion": "2.0",
      "Fields": {
        "code": "NoMatchingBackend",
        "incidentId": "52e06a38-7230-43c2-9e61-bb3498fe3358",
        "message": "No backend matched the given name and projectId\n\n---\n\n* method:     createUpload\n* errorCode:  NoMatchingBackend\n* statusCode: 400\n* time:       2023-06-02T12:50:43.660Z",
        "method": "createArtifact",
        "name": "Error",
        "stack": "Error: No backend matched the given name and projectId\n\n---\n\n* method:     createUpload\n* errorCode:  NoMatchingBackend\n* statusCode: 400\n* time:       2023-06-02T12:50:43.660Z\n    at /app/clients/client/src/client.js:419:19\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async module.exports (/app/clients/client/src/retry.js:18:16)\n    at async Proxy.<anonymous> (/app/services/queue/src/artifacts.js:277:7)",
        "statusCode": 400,
        "v": 1
      },
      "Hostname": "taskcluster-queue-web-84d9fc59b5-vrbcc",
      "Logger": "taskcluster.queue.api",
      "Pid": 1,
      "Severity": 3,
      "Timestamp": 1.685710243663e+18,
      "Type": "monitor.error",
      "message": "Error: No backend matched the given name and projectId\n    at /app/clients/client/src/client.js:419:19\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async module.exports (/app/clients/client/src/retry.js:18:16)\n    at async Proxy.<anonymous> (/app/services/queue/src/artifacts.js:277:7)\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n",
      "requestId": "c3f27da9-f582-404f-a1b1-51b0dfe6c84c",
      "serviceContext": {
        "service": "queue",
        "version": "51.1.0"
      },
      "traceId": "e2cbc17aad5f9081996878e8926527ce"
    },
    "labels": {
      "compute.googleapis.com/resource_name": "gke-taskcluster-commu-default-pool-v1-6fef6e3a-99tl",
      "k8s-pod/app_kubernetes_io/component": "taskcluster-queue-web",
      "k8s-pod/app_kubernetes_io/instance": "communitytc-taskcluster-taskcluster-1",
      "k8s-pod/app_kubernetes_io/name": "taskcluster-queue",
      "k8s-pod/app_kubernetes_io/part-of": "taskcluster",
      "k8s-pod/pod-template-hash": "84d9fc59b5"
    },
    "logName": "projects/moz-fx-taskcluster-prod-4b87/logs/stdout",
    "receiveTimestamp": "2023-06-02T12:51:02.434794157Z",
    "resource": {
      "labels": {
        "cluster_name": "taskcluster-communitytc-v1",
        "container_name": "taskcluster-queue-web",
        "location": "us-west1",
        "namespace_name": "communitytc-taskcluster",
        "pod_name": "taskcluster-queue-web-84d9fc59b5-vrbcc",
        "project_id": "moz-fx-taskcluster-prod-4b87"
      },
      "type": "k8s_container"
    },
    "severity": "ERROR",
    "timestamp": "2023-06-02T12:50:43.663302820Z"
  }
]
```

**Comment by djmitche** [comment]
Yeah, it looks like the object service isn't configured in that deployment:

> No backend matched the given name and projectId

**Comment by djmitche** [comment]
Also, there are a _lot_ of newlines in `.[0].jsonPayload.message`! Any idea what that's about?

**Comment by lotas** [comment]
I've noticed it in some other error messages, not sure where those newlines are coming from. checking
