### ISSUE TITLE
removeWorker fails for instances that are not known to the queue

### ISSUE THREAD

**Issue by lotas** [taskcluster/taskcluster#6328]
```
Error: Request failed: Non-2xx StatusCode: 500 received in 6 attempts
{
  "code": "InternalServerError",
  "message": "Internal Server Error, incidentId eb4b3e78-8e65-4378-b2db-bd4412c33528.\n\n---\n\n* method:     removeWorker\n* errorCode:  InternalServerError\n* statusCode: 500\n* time:       2023-06-14T09:59:13.787Z",
  "requestInfo": {
    "method": "removeWorker",
    "params": {
      "workerPoolId": "gecko-1/b-linux-gcp",
      "workerGroup": "us-central1",
      "workerId": "1433039631257224893"
    },
    "payload": {},
    "time": "2023-06-14T09:59:13.787Z"
  }
}
```

This worker was one of the workers that failed to start and was not calling `claimWork`, so was not known to the queue

https://github.com/taskcluster/taskcluster/blob/main/services/worker-manager/src/api.js#L961-L972

There must have been a reason to do that queue check and to not kill the worker if it is not known to the queue

**Comment by lotas** [comment]
Ah, this is coming from the feature that was introduced in v52 but reverted in v53:

```
Error: Worker with workerId `1433039631257224893`, workerGroup `us-central1`,worker-type `b-linux-gcp` and provisionerId `gecko-1` not found.
    at /app/clients/client/src/client.js:419:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async module.exports (/app/clients/client/src/retry.js:18:16)
    at async GoogleProvider.quarantineWorker (/app/services/worker-manager/src/providers/provider.js:93:5)
    at async GoogleProvider.removeWorker (/app/services/worker-manager/src/providers/google.js:194:5)
    at async Proxy.<anonymous> (/app/services/worker-manager/src/api.js:638:5)
```

Since it got reverted, I think this problem should also go away
