### ISSUE TITLE
Artifact read failure results in missing other artifacts

### ISSUE THREAD

**Issue by jschwartzentruber** [taskcluster/taskcluster#6487]
**Describe the bug**

A directory artifact upload fails on a specific file (log below under additional context).  This causes the task status to be `FAIL` and prevents other artifact uploads from taking place. I expect missing artifacts to be ignored so other artifacts are uploaded.

**To Reproduce**

I don't think this should normally happen. There seems to be a race between the artifact path directory listing and task cleanup processes running to delete temporary files.

**Expected behavior**

I expect all available artifacts to be uploaded, even if there are errors on others.

**Taskcluster version**
generic-worker: 54.4.2

**Additional context**
Original task is here: https://community-tc.services.mozilla.com/tasks/ObSYgXYOSGusjikyWitK0g/runs/1/
```
[taskcluster 2023-08-25T01:15:25.796Z]    Exit Code: 1073807364
[taskcluster 2023-08-25T01:15:25.796Z]    User Time: 15.625ms
[taskcluster 2023-08-25T01:15:25.796Z]  Kernel Time: 62.5ms
[taskcluster 2023-08-25T01:15:25.796Z]    Wall Time: 45m38.4278729s
[taskcluster 2023-08-25T01:15:25.796Z]       Result: FAILED
[taskcluster 2023-08-25T01:15:25.796Z] === Task Finished ===
[taskcluster 2023-08-25T01:15:25.796Z] Task Duration: 45m38.8733679s
[taskcluster 2023-08-25T01:15:26.333Z] Uploading artifact project/fuzzing/site-scout/ffplogs_1m8lj4r5/ffp_log_6_ywfvto.txt from file C:\Users\task_169292327476453\AppData\Local\Temp\site-scout\ffplogs_1m8lj4r5\ffp_log_6_ywfvto.txt with content encoding "gzip", mime type "text/plain; charset=utf-8" and expiry 2023-09-22T00:02:15.462Z
[taskcluster 2023-08-25T01:15:26.751Z] Uploading artifact project/fuzzing/site-scout/ffplogs_1m8lj4r5/ffp_log_8c0yda2q.txt from file C:\Users\task_169292327476453\AppData\Local\Temp\site-scout\ffplogs_1m8lj4r5\ffp_log_8c0yda2q.txt with content encoding "gzip", mime type "text/plain; charset=utf-8" and expiry 2023-09-22T00:02:15.462Z
[taskcluster 2023-08-25T01:15:27.143Z] Uploading artifact project/fuzzing/site-scout/ffplogs_fr472wci/ffp_log_4e3iuza5.txt from file C:\Users\task_169292327476453\AppData\Local\Temp\site-scout\ffplogs_fr472wci\ffp_log_4e3iuza5.txt with content encoding "gzip", mime type "text/plain; charset=utf-8" and expiry 2023-09-22T00:02:15.462Z
[taskcluster 2023-08-25T01:15:27.382Z] Uploading artifact project/fuzzing/site-scout/ffplogs_fr472wci/ffp_log_94xc99cn.txt from file C:\Users\task_169292327476453\AppData\Local\Temp\site-scout\ffplogs_fr472wci\ffp_log_94xc99cn.txt with content encoding "gzip", mime type "text/plain; charset=utf-8" and expiry 2023-09-22T00:02:15.462Z
[taskcluster 2023-08-25T01:15:27.615Z] Uploading artifact project/fuzzing/site-scout/ffprofile_7wug1n02/.startup-incomplete from file C:\Users\task_169292327476453\AppData\Local\Temp\site-scout\ffprofile_7wug1n02\.startup-incomplete with content encoding "gzip", mime type "application/octet-stream" and expiry 2023-09-22T00:02:15.462Z
[taskcluster 2023-08-25T01:15:27.659Z] Uploading link artifact public/logs/live.log to artifact public/logs/live_backing.log with expiry 2023-09-22T00:02:15.462Z
[taskcluster:error] exit status 0x40010004
[taskcluster:error] goroutine 1 [running]:
[taskcluster:error] runtime/debug.Stack()
[taskcluster:error] 	/task_169210859050883/go/go/src/runtime/debug/stack.go:24 +0x5e
[taskcluster:error] main.(*TaskRun).Run.func2()
[taskcluster:error] 	/task_169210859050883/taskcluster/workers/generic-worker/main.go:931 +0x97
[taskcluster:error] panic({0x827820?, 0xc0001d2720?})
[taskcluster:error] 	/task_169210859050883/go/go/src/runtime/panic.go:920 +0x270
[taskcluster:error] github.com/taskcluster/taskcluster/v54/workers/generic-worker/artifacts.(*S3Artifact).createTempFileForPUTBody(0xc0002b2640)
[taskcluster:error] 	/task_169210859050883/taskcluster/workers/generic-worker/artifacts/s3.go:48 +0x2b2
[taskcluster:error] github.com/taskcluster/taskcluster/v54/workers/generic-worker/artifacts.(*S3Artifact).ProcessResponse(0xc0002b2640, {0x7d05c0?, 0xc0002ae050}, {0x9d1608, 0xc00023e000}, {0xc0002b69b0?, 0x41?}, 0x0?)
[taskcluster:error] 	/task_169210859050883/taskcluster/workers/generic-worker/artifacts/s3.go:60 +0x22b
[taskcluster:error] main.(*TaskRun).uploadArtifact(0xc00023e000, {0x9d48f0, 0xc0002b2640})
[taskcluster:error] 	/task_169210859050883/taskcluster/workers/generic-worker/artifacts.go:313 +0x8bb
[taskcluster:error] main.(*TaskRun).Run.func4()
[taskcluster:error] 	/task_169210859050883/taskcluster/workers/generic-worker/main.go:1038 +0x187
[taskcluster:error] main.(*TaskRun).Run(0xc00023e000)
[taskcluster:error] 	/task_169210859050883/taskcluster/workers/generic-worker/main.go:1099 +0x13ab
[taskcluster:error] main.RunWorker()
[taskcluster:error] 	/task_169210859050883/taskcluster/workers/generic-worker/main.go:428 +0xdd9
[taskcluster:error] main.main()
[taskcluster:error] 	/task_169210859050883/taskcluster/workers/generic-worker/main.go:157 +0x565
[taskcluster:error] 
[taskcluster:error] &fs.PathError{Op:"open", Path:"C:\\Users\\task_169292327476453\\AppData\\Local\\Temp\\site-scout\\ffprofile_7wug1n02\\.startup-incomplete", Err:0x2}
[taskcluster:error] open C:\Users\task_169292327476453\AppData\Local\Temp\site-scout\ffprofile_7wug1n02\.startup-incomplete: The system cannot find the file specified.
```

**Comment by Eijebong** [comment]
Looks like the code panics instead of returning an error.
https://github.com/taskcluster/taskcluster/blob/9b0cdd1fdb058294c0074b293cbc5699d7bd9d8a/workers/generic-worker/artifacts/s3.go#L32-L37
After some digging, the panic was introduced by 212a621c30fd8b8fe5979a10e56da597cda3f483 but since that's from 2017 I doubt anyone actually remembers why... Maybe there's some bugzilla bug behind that but I don't know how to search for that.

@petemoore any idea why you did that?

**Comment by petemoore** [comment]
> @petemoore any idea why you did that?

This part above is correct - if Generic Worker can't create a temporary file, it should panic. The actual error Jesse is seeing is a bit further down on line 48, not on line 36. This can be seen in the stack trace:

```
/task_169210859050883/taskcluster/workers/generic-worker/artifacts/s3.go:48 +0x2b2
```

I think I see what is going on.

The task payload includes the following directory artifact:

```
    {
      "expires": "2023-09-22T00:02:15.462742Z",
      "name": "project/fuzzing/site-scout",
      "path": "AppData\\\\Local\\\\Temp\\\\site-scout",
      "type": "directory"
    }
```

On task completion (when the last task command process has completed), Generic Worker scanned this directory, and found several files, including:

* `AppData\Local\Temp\site-scout\ffprofile_7wug1n02\.startup-incomplete`

At this point, Generic Worker has decided that this file exists, and should be uploaded as an artifact. Generic Worker then attempts to read this file in order to upload it here:

https://github.com/taskcluster/taskcluster/blob/9b0cdd1fdb058294c0074b293cbc5699d7bd9d8a/workers/generic-worker/artifacts/s3.go#L46-L49

However, by the time it goes to read the file, it is no longer present. Generic Worker considers this an internal error, since if the file was there when the task processes had already exited, it should be there now when it tries to read the file. It therefore panics.

Note, it should actually resolve the task as exception, not as failure, since an internal error has occurred. I think the problem here may be that generic-worker picks the first failure state it encounters, and it has already decided that the task has failed, and uses this instead of exception. However, I think if ever there is an internal error, even after a task failure, probably the internal error should take precedence over failure, since it indicates something is wrong with the host environment.

In this case, I suspect the OS has deleted the file, because it was in a temp directory, and this is what has caused the problem. It is probably not a good idea having task artifacts in a temp directory, since maybe the OS is free to purge files from those directories at any point after the process that generated them has completed? In any case, something has deleted that file in between the last task command process completing, and then worker uploading the file, so I think it is correct that the code panics, but indeed the task should have resolved as exception rather than failure.

@jschwartzentruber Does this match your understanding of what may have happened? If this is the case, would it be possible to write the task artifacts to a non-temporary directory? Another thing we can do on taskcluster side is to be explicit in docs that it is not supported to have artifacts in a temp directory, and even see if we can find a way to detect it, to generate a malformed payload exception upfront. What do you think?

**Comment by jschwartzentruber** [comment]
I don't believe so. I believe Windows only very recently introduced a feature to automatically remove temporary files on desktop versions, and I can't imagine they would risk that on server versions of Windows. We can create a separate folder for temporary data when running in taskcluster (we're only uploading these as debugging aids), but I don't think it will resolve this issue.

I think more likely is that some task process was still running despite the main shell having exited. Especially given the exit code of the task (0x40010004) which is most likely a shutdown termination (ref: https://stackoverflow.com/q/37078953). My guess is that some task process was slow to exit and release the handle to this file which delayed its deletion.

**Comment by jschwartzentruber** [comment]
Reading a bit on Storage Sense (the temporary cleanup feature in Windows 10+ referenced in the superuser ref above), I stumbled on this script to configure the registry settings:

https://github.com/kaspersmjohansen/StorageSense/blob/main/Configure-StorageSense.ps1

It would be interesting to know if these settings are enabled in the windows imagesets. I don't think they're ever enabled by default, but I don't know where the TC AMIs come from.

**Comment by petemoore** [comment]
> I think more likely is that some task process was still running despite the main shell having exited. Especially given the exit code of the task (0x40010004) which is most likely a shutdown termination (ref: https://stackoverflow.com/q/37078953). My guess is that some task process was slow to exit and release the handle to this file which delayed its deletion.

This is very interesting indeed, and seems like a very reasonable hypothesis. I can provide some details about how the processes are terminated, and perhaps there is some race condition here.

It made me think back to mozilla/community-tc-config#671 and wonder if this is a consequence of us enabling spot instances on GCP. But then I realised that this landed on 1 September, yet the task that had the issue was from 25 August (UTC) so the switch to spot had happened at that point. But I did realise that we have a specific handler for spot termination events in AWS which I don't think we have in GCP, so it could be that we start seeing issues in GCP with tasks being incorrectly resolved when there are spot terminations (in AWS, they will be resolved as exception/worker-shutdown). So it may be that we need to revert mozilla/community-tc-config#671 until we have a handler. Although maybe support for spot terminations in GCP was added in worker runner - I will need to check.

@jschwartzentruber Do you have any idea why the machine might have been shutdown, given that this was before we switched to spot instances? Do you know if the worker pool launch configs had been manually updated to enable spot, and the change just wasn't applied to community-tc-config repo yet?

**Comment by petemoore** [comment]
> But I did realise that we have a specific handler for spot termination events in AWS which I don't think we have in GCP, so it could be that we start seeing issues in GCP with tasks being incorrectly resolved when there are spot terminations (in AWS, they will be resolved as exception/worker-shutdown)

AWS spot termination handling code here: 

https://github.com/taskcluster/taskcluster/blob/8b8c2f92f348dd125177f719e4def3e280d9a34c/tools/worker-runner/provider/aws/awsprovider.go#L122-L136

GCP handling code:

https://github.com/taskcluster/taskcluster/blob/8b8c2f92f348dd125177f719e4def3e280d9a34c/tools/worker-runner/provider/google/google.go#L107-L111

As far as I can tell, the GCP implementation just adds support for sending graceful termination messages to the worker implementation (Generic Worker) from Worker Runner, but nothing actually ever sends the message.

**Comment by jschwartzentruber** [comment]
> Do you have any idea why the machine might have been shut down, given that this was before we switched to spot instances?

We have been using spot instances in proj-fuzzing since January where the worker pools are not generated by community-tc-config, so this could definitely explain it. I looked for where this was handled for AWS and couldn't find it, so I assumed it would just work .. I should have asked. :( 

I have a wip handler for this [here](https://github.com/jschwartzentruber/taskcluster/commit/a9d39f88c66fb0b0db377d5136a0466b7d9fcefd), I'll have to add tests.

**Comment by petemoore** [comment]
> I have a wip handler for this [here](https://github.com/jschwartzentruber/taskcluster/commit/a9d39f88c66fb0b0db377d5136a0466b7d9fcefd), I'll have to add tests.

Many thanks Jesse! I really appreciate you jumping on a fix for this! I've created an issue for it here that you can cross reference against in the changelog: #6530.
