### ISSUE TITLE
generic-worker: "invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by jschwartzentruber** [taskcluster/taskcluster#6488]
**Describe the bug**
Crash in generic-worker while collecting artifacts.

**Expected behavior**
generic-worker should not crash

**Taskcluster version**
generic worker version: 54.4.2

**Additional context**
```
[taskcluster 2023-08-27T00:09:48.676Z] Task Duration: 3m46.1062989s
[taskcluster 2023-08-27T00:09:49.775Z] Uploading link artifact public/logs/live.log to artifact public/logs/live_backing.log with expiry 2023-09-24T00:01:48.744Z
[taskcluster:error] exit status 0x40010004
[taskcluster:error] goroutine 1 [running]:
[taskcluster:error] runtime/debug.Stack()
[taskcluster:error] 	/task_169210859050883/go/go/src/runtime/debug/stack.go:24 +0x5e
[taskcluster:error] main.(*TaskRun).Run.func2()
[taskcluster:error] 	/task_169210859050883/taskcluster/workers/generic-worker/main.go:931 +0x97
[taskcluster:error] panic({0x920fa0?, 0xe773d0?})
[taskcluster:error] 	/task_169210859050883/go/go/src/runtime/panic.go:920 +0x270
[taskcluster:error] main.(*TaskRun).PayloadArtifacts.func1({0xc00013f900?, 0x59?}, {0x0, 0x0}, {0xc000b0f270?, 0x1a?})
[taskcluster:error] 	/task_169210859050883/taskcluster/workers/generic-worker/artifacts.go:79 +0x1c8
[taskcluster:error] path/filepath.walk({0xc000304080, 0x4e}, {0xae5298, 0xc0002d0930}, 0xc000b0f270)
[taskcluster:error] 	/task_169210859050883/go/go/src/path/filepath/path.go:504 +0x1d4
[taskcluster:error] path/filepath.walk({0xc0002dc4c0, 0x3b}, {0xae5298, 0xc0002fe0e0}, 0xc000b0f270)
[taskcluster:error] 	/task_169210859050883/go/go/src/path/filepath/path.go:508 +0x24f
[taskcluster:error] path/filepath.Walk({0xc0002dc4c0, 0x3b}, 0xc000b0f270)
[taskcluster:error] 	/task_169210859050883/go/go/src/path/filepath/path.go:579 +0x66
[taskcluster:error] main.(*TaskRun).PayloadArtifacts(0xc0000f2000)
[taskcluster:error] 	/task_169210859050883/taskcluster/workers/generic-worker/artifacts.go:88 +0x538
[taskcluster:error] main.(*TaskRun).Run.func4()
[taskcluster:error] 	/task_169210859050883/taskcluster/workers/generic-worker/main.go:1028 +0x34
[taskcluster:error] main.(*TaskRun).Run(0xc0000f2000)
[taskcluster:error] 	/task_169210859050883/taskcluster/workers/generic-worker/main.go:1099 +0x13ab
[taskcluster:error] main.RunWorker()
[taskcluster:error] 	/task_169210859050883/taskcluster/workers/generic-worker/main.go:428 +0xdd9
[taskcluster:error] main.main()
[taskcluster:error] 	/task_169210859050883/taskcluster/workers/generic-worker/main.go:157 +0x565
[taskcluster:error] 
[taskcluster:error] "invalid memory address or nil pointer dereference"
[taskcluster:error] runtime error: invalid memory address or nil pointer dereference
```

**Comment by jschwartzentruber** [comment]
The task is here: https://community-tc.services.mozilla.com/tasks/b63xWjEhQSCYU0Rka2bzqA/runs/0/

**Comment by Eijebong** [comment]
If we look at the panic message, we can see `info` in the following function is passed as `nil`.
https://github.com/taskcluster/taskcluster/blob/9b0cdd1fdb058294c0074b293cbc5699d7bd9d8a/workers/generic-worker/artifacts.go#L59

```
[taskcluster:error] main.(*TaskRun).PayloadArtifacts.func1({0xc00013f900?, 0x59?}, {0x0, 0x0}, {0xc000b0f270?, 0x1a?})
[taskcluster:error] 	/task_169210859050883/taskcluster/workers/generic-worker/artifacts.go:79 +0x1c8
```

It's then dereferenced down here which makes it go boom:
https://github.com/taskcluster/taskcluster/blob/9b0cdd1fdb058294c0074b293cbc5699d7bd9d8a/workers/generic-worker/artifacts.go#L79

That function is called by `Walk` which passes nil as `info` when `os.Lstat` fails.

```
func Walk(root string, fn WalkFunc) error {
    info, err := os.Lstat(root)
    if err != nil {
        err = fn(root, nil, err)
    } else {
[...]
```

This comment here is quite funny and probably very wrong :)
https://github.com/taskcluster/taskcluster/blob/9b0cdd1fdb058294c0074b293cbc5699d7bd9d8a/workers/generic-worker/artifacts.go#L60-L62
