### ISSUE TITLE
Intermittent 

### ISSUE THREAD

**Issue by petemoore** [taskcluster/taskcluster#6854]
**Describe the bug**
Getting the following failure in github check "Google Cloud Build / taskcluster (taskcluster-dev)" intermittently:

```
Step #9 - "Smoketest": HTTPError: Response code 503 (Service Temporarily Unavailable) (while executing task __version__ endpoint for github)
```

See e.g. https://github.com/taskcluster/taskcluster/runs/21852513428 which is a github check that ran for a commit on the main branch.

**Comment by lotas** [comment]
Thanks Pete! 
I think we can add some timeouts or retries there, not sure why it took longer for github service to become ready

**Comment by petemoore** [comment]
Looks like this is triggered from cloudbuild.yaml and is running

```
corepack enable && yarn && yarn smoketest
```

So `yarn smoketest` seems to be the culprit.

**Comment by petemoore** [comment]
Looks like there are no retries here:

https://github.com/taskcluster/taskcluster/blob/0a5db6702c48cefd362b9ed10dc47691d60b082f/infrastructure/tooling/src/smoketest/checks/dockerflow.js#L31

Not sure if there are other places with the same problem.

@lotas Do we have a prior art for wrapping "got" http requests with exponential backoff?

**Comment by lotas** [comment]
Thanks Pete,
I don't think there's an issue with this particular implementation of smoketest, as it's being used same way on other envs during deployments and seemed to be running just fine.

There was probably some precondition existing on our dev cluster which delayed the deployment or roll out of newer versions. 
I'll have a look, maybe just a timeout before running smoketest will do the trick

**Comment by lotas** [comment]
To add to my last comment, I don't think timeouts would help. If test fails, it means deployment went wrong, and it is not intermittent, but rather tell about the problem that happened during deployment. 
And this should be investigated individually to see what caused that particular problem. Increasing timeouts or adding backoffs would only delay the failure in such cases

**Comment by matt-boris** [comment]
Just got the following:

```bash
Starting Step #8 - "Smoketest"
Step #8 - "Smoketest": Already have image (with digest): node:22.17.1
Step #8 - "Smoketest": ➤ YN0000: · Yarn 4.9.2
Step #8 - "Smoketest": ➤ YN0000: ┌ Resolution step
Step #8 - "Smoketest": ➤ YN0000: └ Completed in 0s 241ms
Step #8 - "Smoketest": ➤ YN0000: ┌ Post-resolution validation
Step #8 - "Smoketest": ➤ YN0060: │ @octokit/core is listed by your project with version 3.6.0 (p2e6ec), which doesn't satisfy what @octokit/plugin-retry and other dependencies request (^6.1.3).
Step #8 - "Smoketest": ➤ YN0060: │ subscriptions-transport-ws is listed by your project with version 0.11.0 (pbef48), which doesn't satisfy what apollo-link-ws and other dependencies request (~0.9.0).
Step #8 - "Smoketest": ➤ YN0086: │ Some peer dependencies are incorrectly met by your project; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
Step #8 - "Smoketest": ➤ YN0086: │ Some peer dependencies are incorrectly met by dependencies; run yarn explain peer-requirements for details.
Step #8 - "Smoketest": ➤ YN0000: └ Completed
Step #8 - "Smoketest": ➤ YN0000: ┌ Fetch step
Step #8 - "Smoketest": ➤ YN0000: └ Completed in 1s 158ms
Step #8 - "Smoketest": ➤ YN0000: ┌ Link step
Step #8 - "Smoketest": ➤ YN0000: └ Completed in 0s 671ms
Step #8 - "Smoketest": ➤ YN0000: · Done with warnings in 2s 354ms
Step #8 - "Smoketest": Error: Unknown Server Error
Step #8 - "Smoketest":     at file:///workspace/clients/client/src/client.js:426:19
Step #8 - "Smoketest":     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
Step #8 - "Smoketest":     at async default (file:///workspace/clients/client/src/retry.js:18:16)
Step #8 - "Smoketest":     at async main (file:///workspace/infrastructure/tooling/src/smoketest/index.js:26:15) {
Step #8 - "Smoketest":   body: '<html>\r\n' +
Step #8 - "Smoketest":     '<head><title>503 Service Temporarily Unavailable</title></head>\r\n' +
Step #8 - "Smoketest":     '<body>\r\n' +
Step #8 - "Smoketest":     '<center><h1>503 Service Temporarily Unavailable</h1></center>\r\n' +
Step #8 - "Smoketest":     '<hr><center>nginx</center>\r\n' +
Step #8 - "Smoketest":     '</body>\r\n' +
Step #8 - "Smoketest":     '</html>\r\n',
Step #8 - "Smoketest":   code: 'UnknownError',
Step #8 - "Smoketest":   statusCode: 503
Step #8 - "Smoketest": }
Finished Step #8 - "Smoketest"
```

I'm tempted to just toss a small `sleep` at the beginning of the cloudbuild stage to let everything come up and hope we just get a quick/dirty win.
