### ISSUE TITLE
`npm run changelog` no longer works

### ISSUE THREAD

**Issue by bhearsum** [taskcluster/taskcluster#6920]
Since https://github.com/taskcluster/taskcluster/pull/6884 landed I'm no longer able to generate a changelog. For example:
```
~/r/taskcluster action-group *7 ?43 ❯ npm run changelog --minor --users --no-issue              х INT task 4

> taskcluster@62.0.0 changelog
> node infrastructure/tooling/src/main.js changelog

file:///home/bhearsum/repos/taskcluster/infrastructure/tooling/src/utils/docker.js:12
import { rimraf } from 'rimraf';
         ^^^^^^
SyntaxError: Named export 'rimraf' not found. The requested module 'rimraf' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'rimraf';
const { rimraf } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:132:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:214:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async file:///home/bhearsum/repos/taskcluster/infrastructure/tooling/src/main.js:116:21

Node.js v20.11.1
```

I'm _guessing_ this is because I need the new `rimraf`, but `npm install` fails for reasons beyond my comprehension:
```
~/repos/taskcluster action-group *7 ?43 ❯ npm install                                                 task 4
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "link:": link:clients/client

npm ERR! A complete log of this run can be found in: /home/bhearsum/.npm/_logs/2024-03-20T14_48_16_927Z-debug-0.log
```

```
~/repos/taskcluster action-group *7 ?43 ❯ tail -n20 /home/bhearsum/.npm/_logs/2024-03-20T14_48_16_927Z-debug-0.log
104 verbose stack     at #buildDepStep (/home/bhearsum/.config/nvm/versions/node/v20.11.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:917:35)
104 verbose stack     at async Arborist.buildIdealTree (/home/bhearsum/.config/nvm/versions/node/v20.11.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:196:7)
104 verbose stack     at async Promise.all (index 1)
104 verbose stack     at async Arborist.reify (/home/bhearsum/.config/nvm/versions/node/v20.11.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:159:5)
104 verbose stack     at async Install.exec (/home/bhearsum/.config/nvm/versions/node/v20.11.1/lib/node_modules/npm/lib/commands/install.js:152:5)
104 verbose stack     at async module.exports (/home/bhearsum/.config/nvm/versions/node/v20.11.1/lib/node_modules/npm/lib/cli-entry.js:61:5)
105 verbose cwd /home/bhearsum/repos/taskcluster
106 verbose Linux 6.5.0-25-generic
107 verbose node v20.11.1
108 verbose npm  v10.2.4
109 error code EUNSUPPORTEDPROTOCOL
110 error Unsupported URL Type "link:": link:clients/client
111 verbose exit 1
112 timing npm Completed in 2144ms
113 verbose unfinished npm timer reify 1710946097057
114 verbose unfinished npm timer reify:loadTrees 1710946097062
115 verbose unfinished npm timer idealTree:buildDeps 1710946098822
116 verbose unfinished npm timer idealTree:#root 1710946098823
117 verbose code 1
118 error A complete log of this run can be found in: /home/bhearsum/.npm/_logs/2024-03-20T14_48_16_927Z-debug-0.log
```

**Comment by matt-boris** [comment]
This _looks_ to be because you're running the LTS version of Node.js. Go ahead and run `nvm use` in the root directory of the project then maybe try running `yarn` to get all the packages and try again. Please let me know if this helps.

**Comment by matt-boris** [comment]
Also, try using `yarn changelog ...` instead of `npm run changelog ...`

**Comment by lotas** [comment]
yes, `npm install` will fail, as project is heavily dependent on `yarn`, especially with linking internal libs

I can confirm that running `yarn install` is necessary for those linking steps
after that both `yarn run changelog` and `npm run changelog` should be running fine

also, can you please check `npm/yarn info rimraf`? Possibly it was linked to something different. Should be `5.0.5`

**Comment by lotas** [comment]
likely because of recent https://github.com/taskcluster/taskcluster/commit/a7953b2601e6cbdc5a621bce2602ba42dd76b0a2 upgrade of `rimraf`
just `yarn install` :)

**Comment by bhearsum** [comment]
I'm not sure what it was before, but after running `yarn install` I get:
```
~/r/taskcluster action-group *7 !1 ?43 ❯ yarnpkg info rimraf                             Node 18.19.1 task 4
└─ rimraf@npm:5.0.5
   ├─ Version: 5.0.5
   │
   ├─ Exported Binaries
   │  └─ rimraf
   │
   └─ Dependencies
      └─ glob@npm:^10.3.7 → npm:10.3.10
```

I didn't realize `npm` was not supported. After switching to `yarn` things are working again.
