### ISSUE TITLE
worker manager keeps checking  aws instance that doesn't exist

### ISSUE THREAD

**Issue by lotas** [taskcluster/taskcluster#6983]
There are many errors in `worker-manager-workescanner` logs for few AWS instances with this error: 

`The instance ID 'i-0931cb1106ae7c6c7' does not exist` 

<img width="708" alt="image" src="https://github.com/taskcluster/taskcluster/assets/83861/cb13141c-6274-49c7-81be-b0393568c4b6">

Seen in `v64.2.5`, `v64.2.6`

```
InvalidInstanceID.NotFound: The instance ID 'i-0931cb1106ae7c6c7' does not exist
    at throwDefaultError (/app/node_modules/@smithy/smithy-client/dist-cjs/index.js:838:20)
    at /app/node_modules/@smithy/smithy-client/dist-cjs/index.js:847:5
    at de_CommandError (/app/node_modules/@aws-sdk/client-ec2/dist-cjs/index.js:15503:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20
    at async /app/node_modules/@smithy/core/dist-cjs/index.js:165:18
    at async /app/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38
    at async /app/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:33:22
    at async run (/app/node_modules/p-queue/dist/index.js:163:29)
```

Most likely happens in `checkWorker()` but is not handled for some reason

**Comment by lotas** [comment]
<img width="1303" alt="image" src="https://github.com/taskcluster/taskcluster/assets/83861/11ffc1f5-a1db-4805-93d7-c3a2d9311800">

Looks like worker was both alive and dead at the same time. It was requested, started claiming tasks, but `checkWorker()` calls received `InvalidInstanceID.NotFound` error all the time

**Comment by lotas** [comment]
it was likely related to the aws sdk v3 migration, but we haven't noticed this error before
