### ISSUE TITLE
Error with the file src/clients/Object.js in taskcluster-client-web when transpiling it with babel

### ISSUE THREAD

**Issue by julienw** [taskcluster/taskcluster#7110]
**Describe the bug**

When transpiling the file https://github.com/taskcluster/taskcluster/blob/main/clients/client-web/src/clients/Object.js with babel, babel injects a preample:
```js
Object.defineProperty(exports, "__esModule", {
  value: true
});
```

The problem is that because a class named `Object` is created in the same file, `Object.defineProperty` throws an error when parsing:
```
ReferenceError: Cannot access 'Object' before initialization

> 1 | import { Queue } from "taskcluster-client-web";
| ^
2 |

  at Object.<anonymous> (node_modules/taskcluster-client-web/src/clients/Object.js:3:1)
  at Object.require (node_modules/taskcluster-client-web/src/index.js:19:1)
at Object.require (taskcluster-client.test.js:1:1)
```

This happens especially when a project using `taskcluster-client-web` wants to test its code with `jest` (without the ESM configuration).

**To Reproduce**

1. clone the project https://github.com/julienw/taskcluster-object-issue
2. run `npm i`
3. run `npm test`

**Expected behavior**
We should be able to run the library with Jest.

**Taskcluster version**
Library v66.0.0

**Platform (please complete the following information):**

 - OS: Linux

**Additional context**
The fix would be to rename the class named Object to something else, so that it doesn't shadow the JavaScript standard Object class.

Note that Babel is necessary when running with Jest in CommonJS mode because taskcluster-client-web is published with ES modules.

I also reported the issue at Babel: https://github.com/babel/babel/issues/16601

**Comment by julienw** [comment]
An easy fix would be to rename `Object` to something else, but I'm not sure how easy it is given the file seems to be autogenerated?

**Comment by julienw** [comment]
This is why treeherder does his mock in their tests: https://github.com/mozilla/treeherder/blame/master/tests/ui/test-setup.js 
We're doing the same in PerfCompare, but ideally we shouldn't have to do that and be able to test the final requests.

**Comment by lotas** [comment]
Thanks @julienw !
indeed, `Object` collides with a built-in [Object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object)

We can probably add `<Svc>Service`  to the names of the exposed services, will be a breaking change, but it is breaking already so wouldn't be an issue :)

I'll think if there are some other workarounds for this.. maybe we can publish CommonJs version as well or provide some other artifact that would allow to import it slightly differently

**Comment by lotas** [comment]
Since we are generating ESModule only, we can also generate cjs files. Do you think it might solve this one issue to avoid babel transpiling them @julienw ?

**Comment by julienw** [comment]
There would help us for sure, but if you transpile with babel you'll have the same result, I guess?

**Comment by lotas** [comment]
> There would help us for sure, but if you transpile with babel you'll have the same result, I guess?

since we are generating it in the first place, we can also generate cjs and expose both. 

Doesn't solve the shadowing/naming collision with built-in Object, but is an option
