### ISSUE TITLE
Worker Manager: Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by petemoore** [taskcluster/taskcluster#7344]
TypeError: Cannot read properties of undefined (reading 'map')

at Object.<anonymous> (/app/node_modules/@azure/ms-rest-nodeauth/dist/lib/subscriptionManagement/subscriptionUtils.js:70:67)
at Generator.next (<anonymous>)
at fulfilled (/app/node_modules/@azure/ms-rest-nodeauth/dist/lib/subscriptionManagement/subscriptionUtils.js:6:58)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

worker-manager Version 73.0.0

See https://groups.google.com/u/1/a/mozilla.com/g/taskcluster-notifications/c/x6mm2EmIwtc

**Comment by lotas** [comment]
I think this was a one-time thingy:

```
FetchError: request to https://management.azure.com/subscriptions/../resourceGroups/rg-taskcluster-worker-manager-production/providers/Microsoft.Compute/virtualMachines/vm-arqyzogteafht4xf7o13aftgwko5yrvazek/instanceView?api-version=2021-07-01 failed, reason: getaddrinfo EAI_AGAIN management.azure.com 
```

DNS lookup failed? Not sure if we should handle it separately or just let it fail as it is doing now and retry (I assume it is being retried as all cloud api calls https://github.com/taskcluster/taskcluster/blob/21f2aa01be5a5a08b9c084df3267e3fcc01e0000/services/worker-manager/src/providers/cloudapi.js#L92 )
