### ISSUE TITLE
Crash when the downloads directory is missing

### ISSUE THREAD

**Issue by Eijebong** [taskcluster/taskcluster#7369]
Steps to reproduce:

1. Get a task to put something in the downloads folder
2. Remove the downloads folder
3. Run the task again

Version: 72.1.0
Example task: https://taskcluster.bananium.fr/tasks/XG4ARWQHTeapX58w_BPliw

Stacktrace:

```
[taskcluster:error] [mounts] Could not fetch from task TeeslIAUTN-VlQJBv7uKQQ artifact public/image.tar.zst into file downloads/Jkl7ENGbTnued3N5t7SDiA due to open downloads/Jkl7ENGbTnued3N5t7SDiA: no such file or directory
[taskcluster 2024-11-01T20:07:44.960Z] Uploading link artifact public/logs/live.log to artifact public/logs/live_backing.log with expiry 2025-11-01T20:07:40.726Z
[taskcluster:error] [mounts] open downloads/Jkl7ENGbTnued3N5t7SDiA: no such file or directory
[taskcluster:error] goroutine 1 [running]:
[taskcluster:error] runtime/debug.Stack()
[taskcluster:error] 	/home/task_172891650450432/go/go/src/runtime/debug/stack.go:26 +0x5e
[taskcluster:error] main.(*TaskRun).Run.func2()
[taskcluster:error] 	/home/task_172891650450432/taskcluster/workers/generic-worker/main.go:995 +0x9d
[taskcluster:error] panic({0xa71140?, 0x1078e40?})
[taskcluster:error] 	/home/task_172891650450432/go/go/src/runtime/panic.go:785 +0x132
[taskcluster:error] github.com/taskcluster/taskcluster/v72/workers/generic-worker/process.(*Result).ExitCode(...)
[taskcluster:error] 	/home/task_172891650450432/taskcluster/workers/generic-worker/process/process.go:41
[taskcluster:error] main.(*TaskMount).shouldPurgeCaches(0x0?)
[taskcluster:error] 	/home/task_172891650450432/taskcluster/workers/generic-worker/mounts.go:449 +0x3e
[taskcluster:error] main.(*TaskMount).Stop(0xc0003d0480, 0xc00036e768)
[taskcluster:error] 	/home/task_172891650450432/taskcluster/workers/generic-worker/mounts.go:424 +0x32
[taskcluster:error] main.(*TaskRun).Run.func3({{0xc6c650?, 0xc0003d0480?}, {0xc6d480?, 0x10b31e0?}})
[taskcluster:error] 	/home/task_172891650450432/taskcluster/workers/generic-worker/main.go:1083 +0xe9
[taskcluster:error] main.(*TaskRun).Run(0xc0000db008)
[taskcluster:error] 	/home/task_172891650450432/taskcluster/workers/generic-worker/main.go:1087 +0xfab
[taskcluster:error] main.RunWorker()
[taskcluster:error] 	/home/task_172891650450432/taskcluster/workers/generic-worker/main.go:464 +0xb14
[taskcluster:error] main.main()
[taskcluster:error] 	/home/task_172891650450432/taskcluster/workers/generic-worker/main.go:163 +0x5ea
[taskcluster:error] 
[taskcluster:error] "invalid memory address or nil pointer dereference"
[taskcluster:error] runtime error: invalid memory address or nil pointer dereference
```

https://github.com/taskcluster/taskcluster/blob/6f658966e27cae30e34948ec6efff05244d5a712/workers/generic-worker/mounts.go#L147

This function should probably check for `cacheDir` existence too instead of relying for the directory to be there is the state file is.

**Comment by petemoore** [comment]
I don't see this as a bug. If something has deleted the downloads directory, which is managed by generic-worker, it is correct for generic-worker to panic and report the issue. We could improve the error message to say what has happened. If something really wants to delete the downloads directory, it should also delete the generic-worker state files that record what is in that directory. In general it is desirable for the worker to exit if it encounters inconsistent state, since it means something has been changed underneath it, and it could be a security breach. I would argue if something wants to delete that directory, it should also update the generic-worker state files to say it has, rather than leave generic-worker in an inconsistent state.
