### ISSUE TITLE
getLatestArtifact should follow redirects

### ISSUE THREAD

**Issue by bhearsum** [taskcluster/taskcluster#7409]
After https://github.com/taskcluster/taskcluster/issues/4057, the taskcluster client no longer follows any redirects. These days, artifacts are always redirected to elsewhere, eg:
```
~ ❯ curl -I https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/IWLSAEySR9aj2ZQGmPl5_w/runs/0/artifacts/public%2Ftask-graph.json 
HTTP/2 303 
location: https://firefoxci.taskcluster-artifacts.net/IWLSAEySR9aj2ZQGmPl5_w/0/public/task-graph.json
```

...which means that calls to this method in clients end up failing, sometimes cryptically:
```
>>> queue = taskcluster.Queue({"rootUrl": "https://firefox-ci-tc.services.mozilla.com/"})
>>> queue.getLatestArtifact("IWLSAEySR9aj2ZQGmPl5_w", "public/task-graph.json")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bhearsum/.pyenv/versions/taskgraph/lib/python3.11/site-packages/taskcluster/generated/queue.py", line 572, in getLatestArtifact
    return self._makeApiCall(self.funcinfo["getLatestArtifact"], *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bhearsum/.pyenv/versions/taskgraph/lib/python3.11/site-packages/taskcluster/client.py", line 269, in _makeApiCall
    response = self._makeHttpRequest(entry['method'], _route, payload)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bhearsum/.pyenv/versions/taskgraph/lib/python3.11/site-packages/taskcluster/client.py", line 537, in _makeHttpRequest
    raise exceptions.TaskclusterRestFailure(
taskcluster.exceptions.TaskclusterRestFailure: None
```

**Comment by bhearsum** [comment]
sigh, i was using an old client. already fixed in https://github.com/taskcluster/taskcluster/issues/4998
